-- create INTAKE_SERVICE_BRIDGE_FACT table

-- DROP TABLE portal_redux.INTAKE_SERVICE_BRIDGE_FACT;
CREATE TABLE portal_redux.INTAKE_SERVICE_BRIDGE_FACT (
	ID_INTAKE_SERVICE_BRIDGE_FACT int NOT NULL,
	ID_INTAKE_FACT int NULL,
	ID_SERVICE_REFERRAL_DIM int NULL,
	CONSTRAINT PK_ID_INTAKE_SERVICE_BRIDGE_FACT PRIMARY KEY (ID_INTAKE_SERVICE_BRIDGE_FACT),
	CONSTRAINT fk_INTAKE_SERVICE_BRIDGE_FACT_ID_INTAKE_FACT FOREIGN KEY (ID_INTAKE_FACT) REFERENCES portal_redux.INTAKE_FACT(ID_INTAKE_FACT),
	CONSTRAINT fk_INTAKE_SERVICE_BRIDGE_FACT_ID_SERVICE_REFERRAL_DIM FOREIGN KEY (ID_SERVICE_REFERRAL_DIM) REFERENCES portal_redux.SERVICE_REFERRAL_DIM(ID_SERVICE_REFERRAL_DIM)
);

-- load table data

BULK INSERT portal_redux.INTAKE_SERVICE_BRIDGE_FACT
FROM 'D:\S3\fldw-in\INTAKE_SERVICE_BRIDGE_FACT.txt'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);