-- create PLACEMENT_CARE_AUTH_FACT table

-- DROP TABLE portal_redux.PLACEMENT_CARE_AUTH_FACT;
CREATE TABLE portal_redux.PLACEMENT_CARE_AUTH_FACT (
	ID_PLACEMENT_CARE_AUTH_FACT int NOT NULL,
	ID_PLCMNT_CARE_AUTHORITY int NULL,
	ID_CALENDAR_DIM_BEGIN int NULL,
	ID_CALENDAR_DIM_END int NULL,
	ID_PEOPLE_DIM int NULL,
	ID_PLACEMENT_CARE_AUTH_DIM int NULL,
	FL_COMPLETE tinyint NULL,
	FL_VOID tinyint NULL,
	ID_PRSN int NULL,
	CONSTRAINT PK_ID_PLACEMENT_CARE_AUTH_FACT PRIMARY KEY (ID_PLACEMENT_CARE_AUTH_FACT),
	CONSTRAINT fk_PLACEMENT_CARE_AUTH_FACT_ID_CALENDAR_DIM_BEGIN FOREIGN KEY (ID_CALENDAR_DIM_BEGIN) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PLACEMENT_CARE_AUTH_FACT_ID_CALENDAR_DIM_END FOREIGN KEY (ID_CALENDAR_DIM_END) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PLACEMENT_CARE_AUTH_FACT_ID_PEOPLE_DIM FOREIGN KEY (ID_PEOPLE_DIM) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_PLACEMENT_CARE_AUTH_FACT_ID_PLACEMENT_CARE_AUTH_DIM FOREIGN KEY (ID_PLACEMENT_CARE_AUTH_DIM) REFERENCES portal_redux.PLACEMENT_CARE_AUTH_DIM(ID_PLACEMENT_CARE_AUTH_DIM)
);

-- load table data

BULK INSERT portal_redux.PLACEMENT_CARE_AUTH_FACT
FROM 'D:\S3\fldw-in\PLACEMENT_CARE_AUTH_FACT.txt'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);