-- build_rate
-- sixth set of procedures

EXEC portal_redux.prod_build_tbl_prod_build_rate_care_day_maltreatmentintakes;
EXEC portal_redux.prod_build_rate_referrals;
EXEC portal_redux.prod_build_rate_referrals_screened_in;
EXEC portal_redux.prod_build_rate_placement;
EXEC portal_redux.prod_build_rate_placement_order_specific;
EXEC portal_redux.prod_build_rate_referrals_order_specific;
EXEC portal_redux.prod_build_rate_referrals_screened_in_order_specific;
EXEC portal_redux.insert_ref_service_category_flag_xwalk;
