-- create ALLEGATION_FACT table

-- DROP TABLE portal_redux.ALLEGATION_FACT;
CREATE TABLE portal_redux.ALLEGATION_FACT (
	ID_ALLEGATION_FACT int NOT NULL,
	ID_ALGT int NULL,
	ID_CPS int NULL,
	ID_INTAKE_FACT int NULL,
	ID_INVESTIGATION_ASSESSMENT_FACT int NULL,
	ID_ABUSE_TYPE_DIM int NULL,
	ID_CASE_DIM int NULL,
	ID_FINDINGS_DIM int NULL,
	ID_PEOPLE_DIM_SUBJECT int NULL,
	ID_PEOPLE_DIM_VICTIM int NULL,
	ID_RELATIONSHIP_DIM int NULL,
	FL_FATALITY tinyint NULL,
	FL_FATALITY_INVS tinyint NULL,
	FL_INVS tinyint NULL,
	CHILD_AGE tinyint NULL,
	FL_EXPUNGED char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ID_PRSN_SUBJECT int NULL,
	ID_PRSN_VICTIM int NULL,
	ID_CASE int NULL,
	CONSTRAINT PK_ID_ALLEGATION_FACT PRIMARY KEY (ID_ALLEGATION_FACT),
	CONSTRAINT fk_ALLEGATION_FACT_ID_ABUSE_TYPE_DIM FOREIGN KEY (ID_ABUSE_TYPE_DIM) REFERENCES portal_redux.ABUSE_TYPE_DIM(ID_ABUSE_TYPE_DIM),
	CONSTRAINT fk_ALLEGATION_FACT_ID_CASE_DIM FOREIGN KEY (ID_CASE_DIM) REFERENCES portal_redux.CASE_DIM(ID_CASE_DIM),
	CONSTRAINT fk_ALLEGATION_FACT_ID_FINDINGS_DIM FOREIGN KEY (ID_FINDINGS_DIM) REFERENCES portal_redux.FINDINGS_DIM(ID_FINDINGS_DIM),
	CONSTRAINT fk_ALLEGATION_FACT_ID_INTAKE_FACT FOREIGN KEY (ID_INTAKE_FACT) REFERENCES portal_redux.INTAKE_FACT(ID_INTAKE_FACT),
	CONSTRAINT fk_ALLEGATION_FACT_ID_INVESTIGATION_ASSESSMENT_FACT FOREIGN KEY (ID_INVESTIGATION_ASSESSMENT_FACT) REFERENCES portal_redux.INVESTIGATION_ASSESSMENT_FACT(ID_INVESTIGATION_ASSESSMENT_FACT),
	CONSTRAINT fk_ALLEGATION_FACT_ID_PEOPLE_DIM_SUBJECT FOREIGN KEY (ID_PEOPLE_DIM_SUBJECT) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_ALLEGATION_FACT_ID_RELATIONSHIP_DIM FOREIGN KEY (ID_RELATIONSHIP_DIM) REFERENCES portal_redux.RELATIONSHIP_DIM(ID_RELATIONSHIP_DIM)
);
CREATE NONCLUSTERED INDEX idx_id_cps_victim ON dbo.ALLEGATION_FACT (  ID_CPS ASC  , ID_PEOPLE_DIM_VICTIM ASC  )  
	INCLUDE ( ID_ABUSE_TYPE_DIM , ID_PRSN_VICTIM , ID_RELATIONSHIP_DIM ) 
	WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	ON [PRIMARY];
CREATE NONCLUSTERED INDEX idx_id_intake_fact ON dbo.ALLEGATION_FACT (  ID_INTAKE_FACT ASC  )  
	WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	ON [PRIMARY];

-- load table data

BULK INSERT portal_redux.ALLEGATION_FACT
FROM 'D:\S3\fldw-in\ALLEGATION_FACT.TXT'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);