-- Create Table

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [portal_redux].[DISPOSITION_DIM](
	[ID_DISPOSITION_DIM] [int] NOT NULL,
	[CD_INVS_DISP] [int] NULL,
	[TX_INVS_DISP] [varchar](200) NULL,
	[DT_ROW_BEGIN] [datetime] NULL,
	[DT_ROW_END] [datetime] NULL,
	[ID_CYCLE] [int] NULL,
	[IS_CURRENT] [int] NULL,
 CONSTRAINT [PK_ID_DISPOSITION_DIM] PRIMARY KEY CLUSTERED 
(
	[ID_DISPOSITION_DIM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

-- Load Table Data

BULK INSERT [portal_redux].[DISPOSITION_DIM]
FROM  '/Users/mienko/portal_redux/data/DISPOSITION_DIM.TXT'
WITH (
    firstrow = 2, 
    fieldterminator = '|',
    rowterminator = '\n'
)
