-- create INTAKE_PARTICIPANT_FACT table

-- DROP TABLE portal_redux.INTAKE_PARTICIPANT_FACT;
CREATE TABLE portal_redux.INTAKE_PARTICIPANT_FACT (
	ID_INTAKE_PARTICIPANT_FACT int NOT NULL,
	CD_INTK_TYPE int NULL,
	ID_INTK int NULL,
	TS_CR datetime NULL,
	ID_INTAKE_FACT int NULL,
	ID_INTAKE_PARTICIPANT_ROLES_DIM int NULL,
	ID_PEOPLE_DIM_CHILD int NULL,
	TX_INTK_TYPE varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FL_EXPUNGED varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ID_PRSN_CHILD int NULL,
	CONSTRAINT pk_id_INTAKE_PARTICIPANT_FACT PRIMARY KEY (ID_INTAKE_PARTICIPANT_FACT),
	CONSTRAINT fk_INTAKE_PARTICIPANT_FACT_ID_INTAKE_PARTICIPANT_ROLES_DIM FOREIGN KEY (ID_INTAKE_PARTICIPANT_ROLES_DIM) REFERENCES portal_redux.INTAKE_PARTICIPANT_ROLES_DIM(ID_INTAKE_PARTICIPANT_ROLES_DIM),
	CONSTRAINT fk_INTAKE_PARTICIPANT_FACT_ID_PEOPLE_DIM_CHILD FOREIGN KEY (ID_PEOPLE_DIM_CHILD) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM)
);
CREATE NONCLUSTERED INDEX idx_id_intake_fact_incl_roles_dim_child ON portal_redux.INTAKE_PARTICIPANT_FACT (  ID_INTAKE_FACT ASC  )  
	INCLUDE ( ID_INTAKE_PARTICIPANT_ROLES_DIM , ID_PEOPLE_DIM_CHILD ) 
	WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	ON [PRIMARY];

-- load table data

BULK INSERT portal_redux.INTAKE_PARTICIPANT_FACT
FROM 'D:\S3\fldw-in\INTAKE_PARTICIPANT_FACT.txt'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);