-- create LEGAL_TPR_REFERRAL_FACT table

-- DROP TABLE portal_redux.LEGAL_TPR_REFERRAL_FACT;
CREATE TABLE portal_redux.LEGAL_TPR_REFERRAL_FACT (
	ID_LEGAL_TPR_REFERRAL_FACT int NOT NULL,
	ID_LEGAL_TPR_REFERRAL int NULL,
	ID_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT int NULL,
	ID_CALENDAR_DIM_TPR_REFERRAL int NULL,
	ID_RELATIONSHIP_DIM_TPR int NULL,
	ID_PEOPLE_DIM_TPR_PARENT int NULL,
	ID_PRSN_TPR_PARENT int NULL,
	CONSTRAINT pk_ID_LEGAL_TPR_REFERRAL_FACT PRIMARY KEY (ID_LEGAL_TPR_REFERRAL_FACT),
	CONSTRAINT fk_LEGAL_TPR_REFERRAL_FACT_ID_CALENDAR_DIM_TPR_REFERRAL FOREIGN KEY (ID_CALENDAR_DIM_TPR_REFERRAL) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_LEGAL_TPR_REFERRAL_FACT_ID_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT FOREIGN KEY (ID_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT) REFERENCES portal_redux.LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT(ID_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT),
	CONSTRAINT fk_LEGAL_TPR_REFERRAL_FACT_ID_PEOPLE_DIM_TPR_PARENT FOREIGN KEY (ID_PEOPLE_DIM_TPR_PARENT) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_LEGAL_TPR_REFERRAL_FACT_ID_RELATIONSHIP_DIM_TPR FOREIGN KEY (ID_RELATIONSHIP_DIM_TPR) REFERENCES portal_redux.RELATIONSHIP_DIM(ID_RELATIONSHIP_DIM)
);

-- load table data

BULK INSERT portal_redux.LEGAL_TPR_REFERRAL_FACT
FROM 'D:\S3\fldw-in\LEGAL_TPR_REFERRAL_FACT.TXT'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);