-- create LEGAL_JURISDICTION_DIM table

-- DROP TABLE portal_redux.LEGAL_JURISDICTION_DIM;
CREATE TABLE portal_redux.LEGAL_JURISDICTION_DIM (
	ID_LEGAL_JURISDICTION_DIM int NOT NULL,
	CD_JURISDICTION int NULL,
	TX_JURISDICTION varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DT_ROW_BEGIN datetime NULL,
	DT_ROW_END datetime NULL,
	ID_CYCLE int NULL,
	IS_CURRENT int NULL,
	CONSTRAINT PK_ID_LEGAL_JURISDICTION_DIM PRIMARY KEY (ID_LEGAL_JURISDICTION_DIM)
);

-- load table data

BULK INSERT portal_redux.LEGAL_JURISDICTION_DIM
FROM 'D:\S3\fldw-in\LEGAL_JURISDICTION_DIM.TXT'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);