-- create PERMANENCY_FACT definition

-- DROP TABLE portal_redux.PERMANENCY_FACT;
CREATE TABLE portal_redux.PERMANENCY_FACT (
	ID_PERMANENCY_FACT int NOT NULL,
	ID_CRT_DISP int NULL,
	ID_CALENDAR_DIM_HEARING int NULL,
	ID_CALENDAR_DIM_ORDER_ENTERED int NULL,
	ID_CASE_DIM int NULL,
	ID_LEGAL_JURISDICTION_DIM int NULL,
	ID_LEGAL_STATUS_DIM int NULL,
	ID_PEOPLE_DIM int NULL,
	ID_PERMANENCY_PLAN_DIM int NULL,
	CHILD_AGE int NULL,
	ID_PRSN int NULL,
	ID_CASE int NULL,
	CONSTRAINT PK_ID_PERMANENCY_FACT PRIMARY KEY (ID_PERMANENCY_FACT),
	CONSTRAINT fk_PERMANENCY_FACT_ID_CALENDAR_DIM_HEARING FOREIGN KEY (ID_CALENDAR_DIM_HEARING) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PERMANENCY_FACT_ID_CALENDAR_DIM_ORDER_ENTERED FOREIGN KEY (ID_CALENDAR_DIM_ORDER_ENTERED) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PERMANENCY_FACT_ID_CASE_DIM FOREIGN KEY (ID_CASE_DIM) REFERENCES portal_redux.CASE_DIM(ID_CASE_DIM),
	CONSTRAINT fk_PERMANENCY_FACT_ID_LEGAL_JURISDICTION_DIM FOREIGN KEY (ID_LEGAL_JURISDICTION_DIM) REFERENCES portal_redux.LEGAL_JURISDICTION_DIM(ID_LEGAL_JURISDICTION_DIM),
	CONSTRAINT fk_PERMANENCY_FACT_ID_LEGAL_STATUS_DIM FOREIGN KEY (ID_LEGAL_STATUS_DIM) REFERENCES portal_redux.LEGAL_STATUS_DIM(ID_LEGAL_STATUS_DIM),
	CONSTRAINT fk_PERMANENCY_FACT_ID_PEOPLE_DIM FOREIGN KEY (ID_PEOPLE_DIM) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_PERMANENCY_FACT_ID_PERMANENCY_PLAN_DIM FOREIGN KEY (ID_PERMANENCY_PLAN_DIM) REFERENCES portal_redux.PERMANENCY_PLAN_DIM(ID_PERMANENCY_PLAN_DIM)
);

-- load table data

BULK INSERT portal_redux.PERMANENCY_FACT
FROM 'D:\S3\fldw-in\PERMANENCY_FACT.txt'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);