-- create PLACEMENT_CARE_AUTH_DIM table

-- DROP TABLE portal_redux.PLACEMENT_CARE_AUTH_DIM;
CREATE TABLE portal_redux.PLACEMENT_CARE_AUTH_DIM (
	ID_PLACEMENT_CARE_AUTH_DIM int NOT NULL,
	CD_PLACEMENT_CARE_AUTH int NULL,
	TX_PLACEMENT_CARE_AUTH varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_TRIBE int NULL,
	TX_TRIBE varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DT_ROW_BEGIN datetime NULL,
	DT_ROW_END datetime NULL,
	ID_CYCLE int NULL,
	IS_CURRENT int NULL,
	CONSTRAINT PK_ID_PLACEMENT_CARE_AUTH_DIM PRIMARY KEY (ID_PLACEMENT_CARE_AUTH_DIM)
);

-- load table data

BULK INSERT portal_redux.PLACEMENT_CARE_AUTH_DIM
FROM 'D:\S3\fldw-in\PLACEMENT_CARE_AUTH_DIM.txt'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);