-- create PRIMARY_ASSIGNMENT_FACT table

-- DROP TABLE portal_redux.PRIMARY_ASSIGNMENT_FACT;
CREATE TABLE portal_redux.PRIMARY_ASSIGNMENT_FACT (
	ID_PRIMARY_ASSIGNMENT_FACT int NOT NULL,
	ID_CASE int NULL,
	ID_WORKER int NULL,
	ID_CALENDAR_DIM_BEGIN int NULL,
	ID_CALENDAR_DIM_END int NULL,
	ID_CASE_DIM int NULL,
	ID_LOCATION_DIM int NULL,
	ID_WORKER_DIM int NULL,
	ID_WORKER_DIM_CURRENT int NULL,
	CD_ASGN_ROLE int NULL,
	DT_BEGIN datetime NULL,
	DT_END datetime NULL,
	FL_EXPUNGED char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK_ID_PRIMARY_ASSIGNMENT_FACT PRIMARY KEY (ID_PRIMARY_ASSIGNMENT_FACT),
	CONSTRAINT fk_PRIMARY_ASSIGNMENT_FACT_ID_CALENDAR_DIM_BEGIN FOREIGN KEY (ID_CALENDAR_DIM_BEGIN) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PRIMARY_ASSIGNMENT_FACT_ID_CALENDAR_DIM_END FOREIGN KEY (ID_CALENDAR_DIM_END) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PRIMARY_ASSIGNMENT_FACT_ID_CASE_DIM FOREIGN KEY (ID_CASE_DIM) REFERENCES portal_redux.CASE_DIM(ID_CASE_DIM),
	CONSTRAINT fk_PRIMARY_ASSIGNMENT_FACT_ID_LOCATION_DIM FOREIGN KEY (ID_LOCATION_DIM) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_PRIMARY_ASSIGNMENT_FACT_ID_WORKER_DIM FOREIGN KEY (ID_WORKER_DIM) REFERENCES portal_redux.WORKER_DIM(ID_WORKER_DIM),
	CONSTRAINT fk_PRIMARY_ASSIGNMENT_FACT_ID_WORKER_DIM_CURRENT FOREIGN KEY (ID_WORKER_DIM_CURRENT) REFERENCES portal_redux.WORKER_DIM(ID_WORKER_DIM)
);

-- load table data

BULK INSERT portal_redux.PRIMARY_ASSIGNMENT_FACT
FROM 'D:\S3\fldw-in\PRIMARY_ASSIGNMENT_FACT.TXT'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);