-- create REPEAT_MALTREATMENT_FACT table

-- DROP TABLE portal_redux.REPEAT_MALTREATMENT_FACT;
CREATE TABLE portal_redux.REPEAT_MALTREATMENT_FACT (
	ID_REPEAT_MALTREATMENT_FACT int NULL,
	ID_CPS int NULL,
	ID_CPS_PRIOR int NULL,
	ID_PRSN_VCTM int NULL,
	ID_CALENDAR_DIM_PRIOR int NULL,
	ID_CALENDAR_DIM_REPEAT int NULL,
	ID_CASE_DIM int NULL,
	ID_LOCATION_DIM_INCIDENT int NULL,
	ID_LOCATION_DIM_INTAKE_WORKER int NULL,
	ID_LOCATION_DIM_INVESTIGATION_WORKER int NULL,
	ID_LOCATION_DIM_PRIMARY_WORKER int NULL,
	ID_PEOPLE_DIM_VICTIM int NULL,
	ID_PLACEMENT_TYPE_DIM int NULL,
	QT_DAYS_BETWEEN_OCCURRENCE int NULL,
	CHILD_AGE tinyint NULL,
	FL_EXPUNGED char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	id_case int NULL,
	CONSTRAINT fk_REPEAT_MALTREATMENT_FACT_ID_CALENDAR_DIM_PRIOR FOREIGN KEY (ID_CALENDAR_DIM_PRIOR) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_REPEAT_MALTREATMENT_FACT_ID_CALENDAR_DIM_REPEAT FOREIGN KEY (ID_CALENDAR_DIM_REPEAT) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_REPEAT_MALTREATMENT_FACT_ID_CASE_DIM FOREIGN KEY (ID_CASE_DIM) REFERENCES portal_redux.CASE_DIM(ID_CASE_DIM),
	CONSTRAINT fk_REPEAT_MALTREATMENT_FACT_ID_LOCATION_DIM_INCIDENT FOREIGN KEY (ID_LOCATION_DIM_INCIDENT) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_REPEAT_MALTREATMENT_FACT_ID_LOCATION_DIM_INTAKE_WORKER FOREIGN KEY (ID_LOCATION_DIM_INTAKE_WORKER) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_REPEAT_MALTREATMENT_FACT_ID_LOCATION_DIM_INVESTIGATION_WORKER FOREIGN KEY (ID_LOCATION_DIM_INVESTIGATION_WORKER) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_REPEAT_MALTREATMENT_FACT_ID_LOCATION_DIM_PRIMARY_WORKER FOREIGN KEY (ID_LOCATION_DIM_PRIMARY_WORKER) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_REPEAT_MALTREATMENT_FACT_ID_PEOPLE_DIM_VICTIM FOREIGN KEY (ID_PEOPLE_DIM_VICTIM) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_REPEAT_MALTREATMENT_FACT_ID_PLACEMENT_TYPE_DIM FOREIGN KEY (ID_PLACEMENT_TYPE_DIM) REFERENCES portal_redux.PLACEMENT_TYPE_DIM(ID_PLACEMENT_TYPE_DIM)
);

-- load table data

BULK INSERT portal_redux.REPEAT_MALTREATMENT_FACT
FROM 'D:\S3\fldw-in\REPEAT_MALTREATMENT_FACT.txt'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);