-- create SERVICE_FACT table

-- DROP TABLE portal_redux.SERVICE_FACT;
CREATE TABLE portal_redux.SERVICE_FACT (
	ID_SERVICE_FACT int NOT NULL,
	ID_EPSD int NULL,
	ID_REMOVAL_EPISODE_FACT int NULL,
	ID_CALENDAR_DIM_END int NULL,
	ID_CALENDAR_DIM_START int NULL,
	ID_CASE_DIM int NULL,
	ID_LOCATION_DIM_TIME_OF_APPROVAL int NULL,
	ID_PEOPLE_DIM_CHILD int NULL,
	ID_PEOPLE_DIM_SERVICE_RECIPIENT int NULL,
	ID_PLACEMENT_CARE_AUTH_DIM int NULL,
	ID_PLACEMENT_FACT int NULL,
	ID_PLACEMENT_RESULT_DIM int NULL,
	ID_PLACEMENT_TYPE_DIM int NULL,
	ID_PROVIDER_DIM int NULL,
	ID_SERVICE_TYPE_DIM int NULL,
	CD_SSPS_REGION int NULL,
	AM_RATE float NULL,
	AM_UNITS float NULL,
	FL_APPROVED tinyint NULL,
	FL_IN_ERROR tinyint NULL,
	ID_CASE int NULL,
	ID_PRSN_CHILD int NULL,
	ID_PRSN_SERVICE_RECIPIENT int NULL,
	ID_PRVD_ORG int NULL,
	CONSTRAINT PK_ID_SERVICE_FACT PRIMARY KEY (ID_SERVICE_FACT),
	CONSTRAINT fk_SERVICE_FACT_ID_CALENDAR_DIM_END FOREIGN KEY (ID_CALENDAR_DIM_END) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_SERVICE_FACT_ID_CALENDAR_DIM_START FOREIGN KEY (ID_CALENDAR_DIM_START) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_SERVICE_FACT_ID_CASE_DIM FOREIGN KEY (ID_CASE_DIM) REFERENCES portal_redux.CASE_DIM(ID_CASE_DIM),
	CONSTRAINT fk_SERVICE_FACT_ID_LOCATION_DIM_TIME_OF_APPROVAL FOREIGN KEY (ID_LOCATION_DIM_TIME_OF_APPROVAL) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_SERVICE_FACT_ID_PEOPLE_DIM_CHILD FOREIGN KEY (ID_PEOPLE_DIM_CHILD) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_SERVICE_FACT_ID_PEOPLE_DIM_SERVICE_RECIPIENT FOREIGN KEY (ID_PEOPLE_DIM_SERVICE_RECIPIENT) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_SERVICE_FACT_ID_PLACEMENT_CARE_AUTH_DIM FOREIGN KEY (ID_PLACEMENT_CARE_AUTH_DIM) REFERENCES portal_redux.PLACEMENT_CARE_AUTH_DIM(ID_PLACEMENT_CARE_AUTH_DIM),
	CONSTRAINT fk_SERVICE_FACT_ID_PLACEMENT_RESULT_DIM FOREIGN KEY (ID_PLACEMENT_RESULT_DIM) REFERENCES portal_redux.PLACEMENT_RESULT_DIM(ID_PLACEMENT_RESULT_DIM),
	CONSTRAINT fk_SERVICE_FACT_ID_PLACEMENT_TYPE_DIM FOREIGN KEY (ID_PLACEMENT_TYPE_DIM) REFERENCES portal_redux.PLACEMENT_TYPE_DIM(ID_PLACEMENT_TYPE_DIM),
	CONSTRAINT fk_SERVICE_FACT_ID_PROVIDER_DIM FOREIGN KEY (ID_PROVIDER_DIM) REFERENCES portal_redux.PROVIDER_DIM(ID_PROVIDER_DIM),
	CONSTRAINT fk_SERVICE_FACT_ID_SERVICE_TYPE_DIM FOREIGN KEY (ID_SERVICE_TYPE_DIM) REFERENCES portal_redux.SERVICE_TYPE_DIM(ID_SERVICE_TYPE_DIM)
);

-- load table data

BULK INSERT portal_redux.SERVICE_FACT
FROM 'D:\S3\fldw-in\SERVICE_FACT.txt'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);