-- create SIBLING_RELATIONSHIP_FACT table

-- DROP TABLE portal_redux.SIBLING_RELATIONSHIP_FACT;
CREATE TABLE portal_redux.SIBLING_RELATIONSHIP_FACT (
	ID_SIBLING_RELATIONSHIP_FACT int NOT NULL,
	ID_CALENDAR_DIM_BEGIN int NULL,
	ID_CALENDAR_DIM_END int NULL,
	ID_CASE_DIM_CHILD int NULL,
	ID_PEOPLE_DIM_CHILD int NULL,
	ID_PEOPLE_DIM_SIBLING int NULL,
	ID_PLACEMENT_FACT int NULL,
	TX_RELATIONSHIP_TYPE varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FL_SIBLING_IN_PLACEMENT int NULL,
	FL_TOGETHER int NULL,
	CHILD_AGE int NULL,
	SIBLING_AGE int NULL,
	ID_PRSN_CHILD int NULL,
	ID_PRSN_SIBLING int NULL,
	ID_CASE_CHILD int NULL,
	CONSTRAINT PK_ID_SIBLING_RELATIONSHIP_FACT PRIMARY KEY (ID_SIBLING_RELATIONSHIP_FACT),
	CONSTRAINT fk_SIBLING_RELATIONSHIP_FACT_ID_CALENDAR_DIM_BEGIN FOREIGN KEY (ID_CALENDAR_DIM_BEGIN) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_SIBLING_RELATIONSHIP_FACT_ID_CALENDAR_DIM_END FOREIGN KEY (ID_CALENDAR_DIM_END) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_SIBLING_RELATIONSHIP_FACT_ID_CASE_DIM_CHILD FOREIGN KEY (ID_CASE_DIM_CHILD) REFERENCES portal_redux.CASE_DIM(ID_CASE_DIM),
	CONSTRAINT fk_SIBLING_RELATIONSHIP_FACT_ID_PEOPLE_DIM_CHILD FOREIGN KEY (ID_PEOPLE_DIM_CHILD) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_SIBLING_RELATIONSHIP_FACT_ID_PEOPLE_DIM_SIBLING FOREIGN KEY (ID_PEOPLE_DIM_SIBLING) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM)
);

-- load table data

BULK INSERT portal_redux.SIBLING_RELATIONSHIP_FACT
FROM 'D:\S3\fldw-in\SIBLING_RELATIONSHIP_FACT.txt'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);