-- create TRAINING_FACT table

-- DROP TABLE portal_redux.TRAINING_FACT;

CREATE TABLE portal_redux.TRAINING_FACT (
	ID_TRAINING_FACT int NOT NULL,
	ID_PRSN_TRAINING int NULL,
	ID_CALENDAR_DIM_COMPLETION int NULL,
	ID_CALENDAR_DIM_EXPIRATION int NULL,
	ID_PEOPLE_DIM_TRAINING_PARTICIPANT int NULL,
	ID_TRAINING_TYPE_DIM int NULL,
	FL_MEETS_REQUIREMENT int NULL,
	QT_HOURS int NULL,
	FL_EXPUNGED char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ID_PRSN int NULL,
	CONSTRAINT PK__TRAINING__9CF47B22D95C5AB9 PRIMARY KEY (ID_TRAINING_FACT),
	CONSTRAINT fk_TRAINING_FACT_ID_CALENDAR_DIM_COMPLETION FOREIGN KEY (ID_CALENDAR_DIM_COMPLETION) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_TRAINING_FACT_ID_CALENDAR_DIM_EXPIRATION FOREIGN KEY (ID_CALENDAR_DIM_EXPIRATION) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_TRAINING_FACT_ID_PEOPLE_DIM_TRAINING_PARTICIPANT FOREIGN KEY (ID_PEOPLE_DIM_TRAINING_PARTICIPANT) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_TRAINING_FACT_ID_TRAINING_TYPE_DIM FOREIGN KEY (ID_TRAINING_TYPE_DIM) REFERENCES portal_redux.TRAINING_TYPE_DIM(ID_TRAINING_TYPE_DIM)
);

-- load table data

BULK INSERT portal_redux.TRAINING_FACT
FROM 'D:\S3\fldw-in\TRAINING_FACT.TXT'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);