-- create EDUCATION_PLAN_FACT table

-- DROP TABLE portal_redux.EDUCATION_PLAN_FACT;
CREATE TABLE portal_redux.EDUCATION_PLAN_FACT (
	ID_EDUCATION_PLAN_FACT int NOT NULL,
	ID_EDUC_PLAN int NULL,
	ID_CALENDAR_DIM_PLAN_DATE int NULL,
	ID_EDUCATION_PLAN_DIM int NULL,
	ID_PEOPLE_DIM_CHILD int NULL,
	FL_APPLICATIONS int NULL,
	FL_ASSISTANCE int NULL,
	FL_COLLEGE_TOUR int NULL,
	FL_OTHER int NULL,
	FL_POST_PLANNING int NULL,
	FL_EXPUNGED char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ID_PRSN_CHILD int NULL,
	CONSTRAINT PK__EDUCATIO__2C72438EF7628B1B PRIMARY KEY (ID_EDUCATION_PLAN_FACT),
	CONSTRAINT fk_EDUCATION_PLAN_FACT_ID_CALENDAR_DIM_PLAN_DATE FOREIGN KEY (ID_CALENDAR_DIM_PLAN_DATE) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_EDUCATION_PLAN_FACT_ID_EDUCATION_PLAN_DIM FOREIGN KEY (ID_EDUCATION_PLAN_DIM) REFERENCES portal_redux.EDUCATION_PLAN_DIM(ID_EDUCATION_PLAN_DIM),
	CONSTRAINT fk_EDUCATION_PLAN_FACT_ID_PEOPLE_DIM_CHILD FOREIGN KEY (ID_PEOPLE_DIM_CHILD) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM)
);

-- load table data

BULK INSERT portal_redux.EDUCATION_PLAN_FACT
FROM 'D:\S3\fldw-in\EDUCATION_PLAN_FACT.txt'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);