-- create rptPlacement table

-- DROP TABLE portal_redux.rptPlacement;
CREATE TABLE portal_redux.rptPlacement (
	tablekey int NULL,
	id_removal_episode_fact int NOT NULL,
	child int NOT NULL,
	id_case int NULL,
	cd_case_type int NULL,
	tx_case_type varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	tx_region varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	cd_region int NULL,
	tx_office varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	cd_office int NULL,
	tx_county varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	cd_county int NULL,
	primary_worker int NULL,
	worker_region varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	cd_worker_region int NULL,
	worker_office varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	cd_worker_office int NULL,
	worker_county varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	cd_worker_county int NULL,
	worker_unit varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	episode_los int NULL,
	episode_los_grp varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	placement_los int NULL,
	placement_los_grp varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	removal_dt datetime NOT NULL,
	id_calendar_dim_begin int NULL,
	id_epsd int NULL,
	id_placement_fact int NULL,
	latest_plcmnt_dt datetime NULL,
	latest_plcmnt_end_dt datetime NULL,
	last_end_rsn varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	id_prvd_org_caregiver int NULL,
	discharge_dt datetime NULL,
	id_calendar_dim_afcars_end int NULL,
	tx_epsd_type varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	cd_epsd_type int NULL,
	birthdate datetime NULL,
	tx_gndr varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[18bday] int NULL,
	child_age int NULL,
	tx_braam_race varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	tx_multirace varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	setting varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	tx_subctgry varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[relative] int NULL,
	cd_rel int NULL,
	tx_rel varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	current_setting int NULL,
	current_service varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	removal datetime NULL,
	[exit] datetime NULL,
	exit_reason varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	tx_placement_care_auth varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	tx_lgl_stat varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	tx_plcm_dsch_rsn varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	tx_dsch_rsn varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	trh varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ts_up nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	runtime datetime NULL,
	mom_id int NULL,
	dad_id int NULL,
	placement_worker_id int NULL,
	placement_worker_region varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	placement_worker_region_cd int NULL,
	placement_worker_office varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	placement_worker_office_cd int NULL,
	placement_worker_county varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	placement_worker_county_cd int NULL,
	placement_worker_unit int NULL,
	placement_workerint_level int NULL,
	placement_workerint_reason varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	town varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	zip nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	cd_cnty int NULL,
	staddress_type varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	town_type varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	zip_type varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	cnty_type varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	state varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	fl_abandonment int NULL,
	fl_caretaker_inability_cope int NULL,
	fl_child_abuse_alcohol int NULL,
	fl_child_abuses_drug int NULL,
	fl_child_behavior_problems int NULL,
	fl_inadequate_housng int NULL,
	fl_neglect int NULL,
	fl_parent_abuse_alcohol int NULL,
	fl_parent_death int NULL,
	fl_parent_drug_abuse int NULL,
	fl_parent_incarceration int NULL,
	fl_physical_abuse int NULL,
	fl_sex_abuse int NULL,
	fl_relinquishment int NULL,
	primary_ppln varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	cd_primary_ppln int NULL,
	alt_ppln varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	lf_dt datetime NULL,
	cd_alt_ppln int NULL,
	multi_race_mask int NULL,
	cd_hspnc char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	tx_hspnc varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	tx_tribe_name varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[re-entry] varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	fl_false int NULL,
	dt_case_cls datetime NULL,
	[h&s] nvarchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	visit_span nvarchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	lls_dt datetime NULL,
	vpa_lngth int NULL,
	cd_rmvl_mnr int NULL,
	tx_rmvl_mnr varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	cd_placement_care_auth int NULL,
	orig_cd_plcm_dsch_rsn int NULL,
	orig_tx_plcm_dsch_rsn varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	fl_child_clinically_diagnosed int NULL,
	TX_MULTI_RACE_ETHNICITY varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CD_MULTI_RACE_ETHNICITY int NULL,
	removal_qtr datetime NULL,
	discharge_qtr datetime NULL,
	first_setting varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	first_relative int NULL,
	fl_extended_foster_care int NULL,
	tx_placement_care_auth_last varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	cd_placement_care_auth_last int NULL,
    cd_gndr varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	cd_multirace int NULL,
	cd_setting_drvd varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	cd_subctgry int NULL,
	cd_current_service int NULL,
	cd_exit_reason int NULL,
	cd_lgl_stat int NULL,
	cd_plcm_dsch_rsn int NULL,
	cd_tribe_name int NULL,
	cd_dsch_rsn int NULL,
    cd_last_end_rsn int NULL,
	CONSTRAINT PK_rptPlacement PRIMARY KEY (id_removal_episode_fact)
);

-- load table data

BULK INSERT portal_redux.rptPlacement
FROM 'D:\S3\fldw-in\rptPlacement.txt'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);
