-- create TRIBE_FACT table

-- DROP TABLE portal_redux.TRIBE_FACT;
CREATE TABLE portal_redux.TRIBE_FACT (
	ID_TRIBE_FACT int NULL,
	ID_PRSN_TRIBE int NULL,
	ID_TRIBE int NULL,
	ID_CALENDAR_DIM_ENTERED int NULL,
	ID_PEOPLE_DIM int NULL,
	ID_TRIBE_ATTRIBUTE_DIM int NULL,
	ID_TRIBE_DIM int NULL,
	FL_EXPUNGED char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ID_PRSN int NULL,
	CONSTRAINT fk_TRIBE_FACT_ID_CALENDAR_DIM_ENTERED FOREIGN KEY (ID_CALENDAR_DIM_ENTERED) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_TRIBE_FACT_ID_PEOPLE_DIM FOREIGN KEY (ID_PEOPLE_DIM) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_TRIBE_FACT_ID_TRIBE_ATTRIBUTE_DIM FOREIGN KEY (ID_TRIBE_ATTRIBUTE_DIM) REFERENCES portal_redux.TRIBE_ATTRIBUTE_DIM(ID_TRIBE_ATTRIBUTE_DIM),
	CONSTRAINT fk_TRIBE_FACT_ID_TRIBE_DIM FOREIGN KEY (ID_TRIBE_DIM) REFERENCES portal_redux.TRIBE_DIM(ID_TRIBE_DIM)
);

-- load table data

BULK INSERT portal_redux.TRIBE_FACT
FROM 'D:\S3\fldw-in\TRIBE_FACT.txt'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);