-- recreate ooh_dcfs_eps table
DROP TABLE IF EXISTS portal_redux.ooh_dcfs_eps;
CREATE TABLE portal_redux.ooh_dcfs_eps (
	cohort_entry_year								DATETIME			NOT NULL,
	cohort_entry_month								DATETIME			NOT NULL,
	cohort_exit_year								DATETIME			NULL,
	cohort_exit_month								DATETIME			NULL,
	id_prsn_child									INT					NOT NULL,
	birth_dt										DATE				NULL,
	id_removal_episode_fact							INT					NOT NULL,
	discharge_type									VARCHAR(200)		COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	cd_discharge_type								INT					NULL,
	first_removal_dt								DATETIME			NULL,
	fl_first_removal								INT					NOT NULL,
	removal_dt										DATETIME			NOT NULL,
	orig_removal_dt									DATETIME			NOT NULL,
	federal_discharge_date							DATETIME			NULL,
	orig_federal_discharge_date						DATETIME			NULL,
	last_placement_discharge_date					DATETIME			NULL,
	entry_cdc_census_mix_age_cd						INT					NULL,
	entry_census_child_group_cd						INT					NULL,
	entry_developmental_age_cd						INT					NULL,
	exit_cdc_census_mix_age_cd						INT					NULL,
	exit_census_child_group_cd						INT					NULL,
	exit_developmental_age_cd						INT					NULL,
	fl_exit_over_17									SMALLINT			NOT NULL,
	pk_gndr											INT					NULL,
	cd_race_census									INT					NULL,
	census_Hispanic_Latino_Origin_cd				INT					NULL,
	init_cd_plcm_setng								INT					NULL,
	long_cd_plcm_setng								INT					NULL,
	Removal_County_Cd								INT					NULL,
	exit_county_cd									INT					NULL,
	entry_int_match_param_key_cdc_census_mix		DECIMAL(9,0)		NULL,
	entry_int_match_param_key_census_child_group	DECIMAL(9,0)		NULL,
	entry_int_match_param_key_developmental			DECIMAL(9,0)		NULL,
	exit_int_match_param_key_cdc_census_mix			DECIMAL(9,0)		NULL,
	exit_int_match_param_key_census_child_group		DECIMAL(9,0)		NULL,
	exit_int_match_param_key_developmental			DECIMAL(9,0)		NULL,
	bin_dep_cd										INT					NULL,
	max_bin_los_cd									INT					NULL,
	bin_placement_cd								INT					NULL,
	cd_reporter_type								INT					NULL,
	fl_cps_invs										INT					NULL,
	fl_cfws											INT					NULL,
	fl_risk_only									INT					NULL,
	fl_alternate_intervention						INT					NULL,
	fl_frs											INT					NULL,
	fl_dlr											INT					NULL,
	fl_far											INT					NULL,
	fl_phys_abuse									INT					NOT NULL,
	fl_sexual_abuse									INT					NOT NULL,
	fl_neglect										INT					NOT NULL,
	fl_any_legal									INT					NOT NULL,
	fl_founded_phys_abuse							INT					NOT NULL,
	fl_founded_sexual_abuse							INT					NOT NULL,
	fl_founded_neglect								INT					NOT NULL,
	fl_found_any_legal								INT					NOT NULL,
	bin_ihs_svc_cd									INT					NULL,
	prsn_cnt										INT					NOT NULL,
	exit_within_month_mult3							INT					NULL,
	nxt_reentry_within_min_month_mult3				INT					NULL,
	fl_nondcfs_eps									INT					NOT NULL,
	fl_nondcfs_within_eps							INT					NOT NULL,
	fl_nondcfs_overlap_eps							INT					NOT NULL,
	dependency_dt									DATETIME			NULL,
	fl_dep_exist									INT					NULL,
	fl_reentry										INT NOT				NULL,
	next_reentry_date								DATETIME			NULL,
	child_eps_rank_asc								INT					NULL,
	child_eps_rank_desc								INT					NULL,
	id_case											INT					NULL,
	CONSTRAINT pk_ooh_dcfs_eps PRIMARY KEY (id_prsn_child, removal_dt)
);
CREATE NONCLUSTERED INDEX idx_age_census_child_age_grp_federal_discharge_date_in ON portal_redux.ooh_dcfs_eps (exit_census_child_group_cd ASC, federal_discharge_date ASC)
	INCLUDE (bin_dep_cd, bin_ihs_svc_cd, bin_placement_cd, birth_dt, cd_discharge_type, cd_race_census, cd_reporter_type, census_Hispanic_Latino_Origin_cd, child_eps_rank_asc, child_eps_rank_desc, cohort_entry_month, cohort_entry_year, cohort_exit_month, cohort_exit_year, dependency_dt, discharge_type, entry_cdc_census_mix_age_cd, entry_census_child_group_cd, entry_int_match_param_key_cdc_census_mix, entry_int_match_param_key_census_child_group, exit_cdc_census_mix_age_cd, exit_county_cd, exit_int_match_param_key_cdc_census_mix, exit_int_match_param_key_census_child_group, exit_within_month_mult3, first_removal_dt, fl_alternate_intervention, fl_any_legal, fl_cfws, fl_cps_invs, fl_dep_exist, fl_first_removal, fl_found_any_legal, fl_founded_neglect, fl_founded_phys_abuse, fl_founded_sexual_abuse, fl_frs, fl_neglect, fl_nondcfs_eps, fl_nondcfs_overlap_eps, fl_nondcfs_within_eps, fl_phys_abuse, fl_reentry, fl_risk_only, fl_sexual_abuse, id_prsn_child, id_removal_episode_fact, init_cd_plcm_setng, last_placement_discharge_date, long_cd_plcm_setng, max_bin_los_cd, next_reentry_date, nxt_reentry_within_min_month_mult3, orig_federal_discharge_date, orig_removal_dt, pk_gndr, prsn_cnt, Removal_County_Cd, removal_dt)
	WITH (PAD_INDEX = OFF, FILLFACTOR = 100, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
CREATE NONCLUSTERED INDEX idx_federal_discharge_date_ooh_dcfs_eps ON portal_redux.ooh_dcfs_eps (federal_discharge_date ASC)
	INCLUDE (birth_dt, exit_county_cd, id_prsn_child, max_bin_los_cd, pk_gndr, removal_dt)
    WITH (PAD_INDEX = OFF, FILLFACTOR = 100, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
CREATE NONCLUSTERED INDEX idx_poc1ab_1 ON portal_redux.ooh_dcfs_eps (removal_dt ASC, federal_discharge_date ASC, id_removal_episode_fact ASC, birth_dt ASC)
	INCLUDE (id_prsn_child)
	WITH (PAD_INDEX = OFF, FILLFACTOR = 100, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
