-- adds back constraints removed before loading current quarter's data (rows are added in later scripts)
-- run after 'load_base_data.sql'


ALTER TABLE portal_redux.ABUSE_FACT
ADD CONSTRAINT fk_ID_CALENDAR_DIM_INCIDENT FOREIGN KEY (ID_CALENDAR_DIM_INCIDENT) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_ID_CALENDAR_DIM_REFERRED FOREIGN KEY (ID_CALENDAR_DIM_REFERRED) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_id_calendar_dim_founded FOREIGN KEY (ID_CALENDAR_DIM_FOUNDED) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_ID_CASE_DIM FOREIGN KEY (ID_CASE_DIM) REFERENCES portal_redux.CASE_DIM(ID_CASE_DIM),
	CONSTRAINT fk_ID_LOCATION_DIM_INCIDENT FOREIGN KEY (ID_LOCATION_DIM_INCIDENT) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_ID_LOCATION_DIM_INTAKE_WORKER FOREIGN KEY (ID_LOCATION_DIM_INTAKE_WORKER) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_ID_LOCATION_DIM_PRIMARY_WORKER FOREIGN KEY (ID_LOCATION_DIM_PRIMARY_WORKER) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_ID_PEOPLE_DIM_VICTIM FOREIGN KEY (ID_PEOPLE_DIM_VICTIM) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_ID_PLACEMENT_TYPE_DIM FOREIGN KEY (ID_PLACEMENT_TYPE_DIM) REFERENCES portal_redux.PLACEMENT_TYPE_DIM(ID_PLACEMENT_TYPE_DIM),
	CONSTRAINT fk_ID_PROVIDER_DIM FOREIGN KEY (ID_PROVIDER_DIM) REFERENCES portal_redux.PROVIDER_DIM(ID_PROVIDER_DIM),
	CONSTRAINT fk_ID_WORKER_DIM_PRIMARY FOREIGN KEY (ID_WORKER_DIM_PRIMARY) REFERENCES portal_redux.WORKER_DIM(ID_WORKER_DIM);


ALTER TABLE portal_redux.ALLEGATION_FACT 
ADD CONSTRAINT fk_ALLEGATION_FACT_ID_ABUSE_TYPE_DIM FOREIGN KEY (ID_ABUSE_TYPE_DIM) REFERENCES portal_redux.ABUSE_TYPE_DIM(ID_ABUSE_TYPE_DIM),
	CONSTRAINT fk_ALLEGATION_FACT_ID_CASE_DIM FOREIGN KEY (ID_CASE_DIM) REFERENCES portal_redux.CASE_DIM(ID_CASE_DIM),
	CONSTRAINT fk_ALLEGATION_FACT_ID_FINDINGS_DIM FOREIGN KEY (ID_FINDINGS_DIM) REFERENCES portal_redux.FINDINGS_DIM(ID_FINDINGS_DIM),
	--CONSTRAINT fk_ALLEGATION_FACT_ID_INTAKE_FACT FOREIGN KEY (ID_INTAKE_FACT) REFERENCES portal_redux.INTAKE_FACT(ID_INTAKE_FACT), -- issues running this line
	CONSTRAINT fk_ALLEGATION_FACT_ID_INVESTIGATION_ASSESSMENT_FACT FOREIGN KEY (ID_INVESTIGATION_ASSESSMENT_FACT) REFERENCES portal_redux.INVESTIGATION_ASSESSMENT_FACT(ID_INVESTIGATION_ASSESSMENT_FACT),
	CONSTRAINT fk_ALLEGATION_FACT_ID_PEOPLE_DIM_SUBJECT FOREIGN KEY (ID_PEOPLE_DIM_SUBJECT) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_ALLEGATION_FACT_ID_RELATIONSHIP_DIM FOREIGN KEY (ID_RELATIONSHIP_DIM) REFERENCES portal_redux.RELATIONSHIP_DIM(ID_RELATIONSHIP_DIM);


ALTER TABLE portal_redux.ASSIGNMENT_FACT
ADD CONSTRAINT fk_ASSIGNMENT_FACT_ID_ASSIGNMENT_ATTRIBUTE_DIM FOREIGN KEY (ID_ASSIGNMENT_ATTRIBUTE_DIM) REFERENCES portal_redux.ASSIGNMENT_ATTRIBUTE_DIM(ID_ASSIGNMENT_ATTRIBUTE_DIM),
	CONSTRAINT fk_ASSIGNMENT_FACT_ID_CALENDAR_DIM_BEGIN FOREIGN KEY (ID_CALENDAR_DIM_BEGIN) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_ASSIGNMENT_FACT_ID_CALENDAR_DIM_END FOREIGN KEY (ID_CALENDAR_DIM_END) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_ASSIGNMENT_FACT_ID_CASE_DIM FOREIGN KEY (ID_CASE_DIM) REFERENCES portal_redux.CASE_DIM(ID_CASE_DIM),
	CONSTRAINT fk_ASSIGNMENT_FACT_ID_LOCATION_DIM FOREIGN KEY (ID_LOCATION_DIM) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_ASSIGNMENT_FACT_ID_PEOPLE_DIM FOREIGN KEY (ID_PEOPLE_DIM) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_ASSIGNMENT_FACT_ID_PROVIDER_DIM FOREIGN KEY (ID_PROVIDER_DIM) REFERENCES portal_redux.PROVIDER_DIM(ID_PROVIDER_DIM),
	CONSTRAINT fk_ASSIGNMENT_FACT_ID_WORKER_DIM FOREIGN KEY (ID_WORKER_DIM) REFERENCES portal_redux.WORKER_DIM(ID_WORKER_DIM);


ALTER TABLE portal_redux.CASE_DIM
ADD CONSTRAINT fk_CASE_DIM_ID_CALENDAR_DIM_LAST_ACTIVITY FOREIGN KEY (ID_CALENDAR_DIM_LAST_ACTIVITY) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_CASE_DIM_ID_LOCATION_DIM FOREIGN KEY (ID_LOCATION_DIM) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM);


ALTER TABLE portal_redux.EDUCATION_PLAN_FACT
ADD CONSTRAINT fk_EDUCATION_PLAN_FACT_ID_CALENDAR_DIM_PLAN_DATE FOREIGN KEY (ID_CALENDAR_DIM_PLAN_DATE) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_EDUCATION_PLAN_FACT_ID_EDUCATION_PLAN_DIM FOREIGN KEY (ID_EDUCATION_PLAN_DIM) REFERENCES portal_redux.EDUCATION_PLAN_DIM(ID_EDUCATION_PLAN_DIM),
	CONSTRAINT fk_EDUCATION_PLAN_FACT_ID_PEOPLE_DIM_CHILD FOREIGN KEY (ID_PEOPLE_DIM_CHILD) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM);


ALTER TABLE portal_redux.IL_ANSELL_CASEY_ASSESSMENT_FACT
ADD CONSTRAINT fk_IL_ANSELL_CASEY_ASSESSMENT_FACT_ID_INDEPENDENT_LIVING_FACT FOREIGN KEY (ID_INDEPENDENT_LIVING_FACT) REFERENCES portal_redux.INDEPENDENT_LIVING_FACT(ID_INDEPENDENT_LIVING_FACT);


ALTER TABLE portal_redux.IL_NYTD_QUESTIONS_FACT
ADD CONSTRAINT fk_IL_NYTD_QUESTIONS_FACT_ID_CALENDAR_DIM_SURVEY_COMPLETED FOREIGN KEY (ID_CALENDAR_DIM_SURVEY_COMPLETED) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_IL_NYTD_QUESTIONS_FACT_ID_IL_NYTD_QUESTIONS_ATTRIBUTE_DIM FOREIGN KEY (ID_IL_NYTD_QUESTIONS_ATTRIBUTE_DIM) REFERENCES portal_redux.IL_NYTD_QUESTIONS_ATTRIBUTE_DIM(ID_IL_NYTD_QUESTIONS_ATTRIBUTE_DIM),
	CONSTRAINT fk_IL_NYTD_QUESTIONS_FACT_ID_INDEPENDENT_LIVING_FACT FOREIGN KEY (ID_INDEPENDENT_LIVING_FACT) REFERENCES portal_redux.INDEPENDENT_LIVING_FACT(ID_INDEPENDENT_LIVING_FACT);


ALTER TABLE portal_redux.INDEPENDENT_LIVING_FACT
ADD CONSTRAINT fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_ANTICIPATED_OUT_CARE FOREIGN KEY (ID_CALENDAR_DIM_ANTICIPATED_OUT_CARE) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_BEGAN FOREIGN KEY (ID_CALENDAR_DIM_BEGAN) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_IL_PLAN_COMPLETED FOREIGN KEY (ID_CALENDAR_DIM_IL_PLAN_COMPLETED) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_INITIAL_IL_REFERRAL FOREIGN KEY (ID_CALENDAR_DIM_INITIAL_IL_REFERRAL) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_REFERRED FOREIGN KEY (ID_CALENDAR_DIM_REFERRED) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_YOUTH_NOT_PARTICIPATING FOREIGN KEY (ID_CALENDAR_DIM_YOUTH_NOT_PARTICIPATING) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INDEPENDENT_LIVING_FACT_ID_PEOPLE_DIM FOREIGN KEY (ID_PEOPLE_DIM) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM);


ALTER TABLE portal_redux.INTAKE_FACT
ADD CONSTRAINT fk_INTAKE_FACT_ID_CALENDAR_DIM_ACCESS_RCVD FOREIGN KEY (ID_CALENDAR_DIM_ACCESS_RCVD) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INTAKE_FACT_ID_CALENDAR_DIM_CPS_SPVR_DSCN FOREIGN KEY (ID_CALENDAR_DIM_CPS_SPVR_DSCN) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INTAKE_FACT_ID_CALENDAR_DIM_INCD FOREIGN KEY (ID_CALENDAR_DIM_INCD) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INTAKE_FACT_ID_CALENDAR_DIM_SPVR_DSCN FOREIGN KEY (ID_CALENDAR_DIM_SPVR_DSCN) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INTAKE_FACT_ID_CALENDAR_DIM_WRKR_DSCN FOREIGN KEY (ID_CALENDAR_DIM_WRKR_DSCN) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INTAKE_FACT_ID_CASE_DIM FOREIGN KEY (ID_CASE_DIM) REFERENCES portal_redux.CASE_DIM(ID_CASE_DIM),
	CONSTRAINT fk_INTAKE_FACT_ID_INTAKE_ATTRIBUTE_DIM FOREIGN KEY (ID_INTAKE_ATTRIBUTE_DIM) REFERENCES portal_redux.INTAKE_ATTRIBUTE_DIM(ID_INTAKE_ATTRIBUTE_DIM),
	CONSTRAINT fk_INTAKE_FACT_ID_INTAKE_TYPE_DIM FOREIGN KEY (ID_INTAKE_TYPE_DIM) REFERENCES portal_redux.INTAKE_TYPE_DIM(ID_INTAKE_TYPE_DIM),
	CONSTRAINT fk_INTAKE_FACT_ID_LOCATION_DIM_INTAKE_WORKER FOREIGN KEY (ID_LOCATION_DIM_INTAKE_WORKER) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_INTAKE_FACT_ID_PROVIDER_DIM_INTAKE FOREIGN KEY (ID_PROVIDER_DIM_INTAKE) REFERENCES portal_redux.PROVIDER_DIM(ID_PROVIDER_DIM),
	CONSTRAINT fk_INTAKE_FACT_ID_RESPONSE_TIME_EXP_DIM FOREIGN KEY (ID_RESPONSE_TIME_EXP_DIM) REFERENCES portal_redux.RESPONSE_TIME_EXP_DIM(ID_RESPONSE_TIME_EXP_DIM),
	CONSTRAINT fk_INTAKE_FACT_ID_WORKER_DIM_CPS_SUPERVISOR FOREIGN KEY (ID_WORKER_DIM_CPS_SUPERVISOR) REFERENCES portal_redux.WORKER_DIM(ID_WORKER_DIM),
	CONSTRAINT fk_INTAKE_FACT_ID_WORKER_DIM_INTAKE FOREIGN KEY (ID_WORKER_DIM_INTAKE) REFERENCES portal_redux.WORKER_DIM(ID_WORKER_DIM),
	CONSTRAINT fk_INTAKE_FACT_ID_WORKER_DIM_INTAKE_SUPERVISOR FOREIGN KEY (ID_WORKER_DIM_INTAKE_SUPERVISOR) REFERENCES portal_redux.WORKER_DIM(ID_WORKER_DIM);


ALTER TABLE portal_redux.INTAKE_PARTICIPANT_FACT
ADD CONSTRAINT fk_INTAKE_PARTICIPANT_FACT_ID_INTAKE_PARTICIPANT_ROLES_DIM FOREIGN KEY (ID_INTAKE_PARTICIPANT_ROLES_DIM) REFERENCES portal_redux.INTAKE_PARTICIPANT_ROLES_DIM(ID_INTAKE_PARTICIPANT_ROLES_DIM),
	CONSTRAINT fk_INTAKE_PARTICIPANT_FACT_ID_PEOPLE_DIM_CHILD FOREIGN KEY (ID_PEOPLE_DIM_CHILD) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM);


ALTER TABLE portal_redux.INTAKE_SERVICE_BRIDGE_FACT
ADD CONSTRAINT fk_INTAKE_SERVICE_BRIDGE_FACT_ID_INTAKE_FACT FOREIGN KEY (ID_INTAKE_FACT) REFERENCES portal_redux.INTAKE_FACT(ID_INTAKE_FACT),
	CONSTRAINT fk_INTAKE_SERVICE_BRIDGE_FACT_ID_SERVICE_REFERRAL_DIM FOREIGN KEY (ID_SERVICE_REFERRAL_DIM) REFERENCES portal_redux.SERVICE_REFERRAL_DIM(ID_SERVICE_REFERRAL_DIM);


ALTER TABLE portal_redux.INTAKE_VICTIM_FACT
ADD CONSTRAINT fk_INTAKE_VICTIM_FACT_ID_CALENDAR_DIM_DUE FOREIGN KEY (ID_CALENDAR_DIM_DUE) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INTAKE_VICTIM_FACT_ID_CALENDAR_DIM_DUE_ORIGINAL FOREIGN KEY (ID_CALENDAR_DIM_DUE_ORIGINAL) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INTAKE_VICTIM_FACT_ID_CALENDAR_DIM_IFF_RESPONSE_ATTEMPT FOREIGN KEY (ID_CALENDAR_DIM_IFF_RESPONSE_ATTEMPT) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INTAKE_VICTIM_FACT_ID_CALENDAR_DIM_IFF_RESPONSE_COMPLETED FOREIGN KEY (ID_CALENDAR_DIM_IFF_RESPONSE_COMPLETED) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INTAKE_VICTIM_FACT_ID_CALENDAR_DIM_VICTIM_ADDED FOREIGN KEY (ID_CALENDAR_DIM_VICTIM_ADDED) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INTAKE_VICTIM_FACT_ID_RESPONSE_TIME_EXP_DIM FOREIGN KEY (ID_RESPONSE_TIME_EXP_DIM) REFERENCES portal_redux.RESPONSE_TIME_EXP_DIM(ID_RESPONSE_TIME_EXP_DIM),
	CONSTRAINT fk_INTAKE_VICTIM_FACT_IID_CALENDAR_DIM_VICTIM_ADDED FOREIGN KEY (ID_CALENDAR_DIM_VICTIM_ADDED) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM);


ALTER TABLE portal_redux.INVESTIGATION_ASSESSMENT_FACT
ADD CONSTRAINT fk_INVESTIGATION_ASSESSMENT_FACT_ID_CALENDAR_DIM_LEVEL1_APPROVED FOREIGN KEY (ID_CALENDAR_DIM_LEVEL1_APPROVED) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INVESTIGATION_ASSESSMENT_FACT_ID_CALENDAR_DIM_LEVEL2_APPROVED FOREIGN KEY (ID_CALENDAR_DIM_LEVEL2_APPROVED) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INVESTIGATION_ASSESSMENT_FACT_ID_CASE_DIM FOREIGN KEY (ID_CASE_DIM) REFERENCES portal_redux.CASE_DIM(ID_CASE_DIM),
	CONSTRAINT fk_INVESTIGATION_ASSESSMENT_FACT_ID_DISPOSITION_DIM FOREIGN KEY (ID_DISPOSITION_DIM) REFERENCES portal_redux.DISPOSITION_DIM(ID_DISPOSITION_DIM),
	CONSTRAINT fk_INVESTIGATION_ASSESSMENT_FACT_ID_INVESTIGATION_TYPE_DIM FOREIGN KEY (ID_INVESTIGATION_TYPE_DIM) REFERENCES portal_redux.INVESTIGATION_TYPE_DIM(ID_INVESTIGATION_TYPE_DIM),
	CONSTRAINT fk_INVESTIGATION_ASSESSMENT_FACT_ID_LOCATION_DIM FOREIGN KEY (ID_LOCATION_DIM) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_INVESTIGATION_ASSESSMENT_FACT_ID_PROVIDER_DIM FOREIGN KEY (ID_PROVIDER_DIM) REFERENCES portal_redux.PROVIDER_DIM(ID_PROVIDER_DIM),
	CONSTRAINT fk_INVESTIGATION_ASSESSMENT_FACT_ID_WORKER_DIM FOREIGN KEY (ID_WORKER_DIM) REFERENCES portal_redux.WORKER_DIM(ID_WORKER_DIM);


ALTER TABLE portal_redux.LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT
ADD CONSTRAINT fk_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT_ID_CALENDAR_DIM_FINDING FOREIGN KEY (ID_CALENDAR_DIM_FINDING) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT_ID_CASE_DIM FOREIGN KEY (ID_CASE_DIM) REFERENCES portal_redux.CASE_DIM(ID_CASE_DIM),
	CONSTRAINT fk_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT_ID_PEOPLE_DIM FOREIGN KEY (ID_PEOPLE_DIM) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM);


ALTER TABLE portal_redux.LEGAL_FACT
ADD CONSTRAINT fk_LEGAL_FACT_ID_CALENDAR_DIM_EFFECTIVE FOREIGN KEY (ID_CALENDAR_DIM_EFFECTIVE) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_LEGAL_FACT_ID_CALENDAR_DIM_HEARING FOREIGN KEY (ID_CALENDAR_DIM_HEARING) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_LEGAL_FACT_ID_CASE_DIM FOREIGN KEY (ID_CASE_DIM) REFERENCES portal_redux.CASE_DIM(ID_CASE_DIM),
	CONSTRAINT fk_LEGAL_FACT_ID_LEGAL_ACTION_DIM FOREIGN KEY (ID_LEGAL_ACTION_DIM) REFERENCES portal_redux.LEGAL_ACTION_DIM(ID_LEGAL_ACTION_DIM),
	CONSTRAINT fk_LEGAL_FACT_ID_LEGAL_JURISDICTION_DIM FOREIGN KEY (ID_LEGAL_JURISDICTION_DIM) REFERENCES portal_redux.LEGAL_JURISDICTION_DIM(ID_LEGAL_JURISDICTION_DIM),
	CONSTRAINT fk_LEGAL_FACT_ID_LEGAL_RESULT_DIM FOREIGN KEY (ID_LEGAL_RESULT_DIM) REFERENCES portal_redux.LEGAL_RESULT_DIM(ID_LEGAL_RESULT_DIM),
	CONSTRAINT fk_LEGAL_FACT_ID_LEGAL_STATUS_DIM FOREIGN KEY (ID_LEGAL_STATUS_DIM) REFERENCES portal_redux.LEGAL_STATUS_DIM(ID_LEGAL_STATUS_DIM),
	CONSTRAINT fk_LEGAL_FACT_ID_PEOPLE_DIM FOREIGN KEY (ID_PEOPLE_DIM) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_LEGAL_FACT_ID_WORKER_DIM FOREIGN KEY (ID_WORKER_DIM) REFERENCES portal_redux.WORKER_DIM(ID_WORKER_DIM);


ALTER TABLE portal_redux.LEGAL_TPR_REFERRAL_FACT
ADD CONSTRAINT fk_LEGAL_TPR_REFERRAL_FACT_ID_CALENDAR_DIM_TPR_REFERRAL FOREIGN KEY (ID_CALENDAR_DIM_TPR_REFERRAL) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_LEGAL_TPR_REFERRAL_FACT_ID_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT FOREIGN KEY (ID_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT) REFERENCES portal_redux.LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT(ID_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT),
	CONSTRAINT fk_LEGAL_TPR_REFERRAL_FACT_ID_PEOPLE_DIM_TPR_PARENT FOREIGN KEY (ID_PEOPLE_DIM_TPR_PARENT) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_LEGAL_TPR_REFERRAL_FACT_ID_RELATIONSHIP_DIM_TPR FOREIGN KEY (ID_RELATIONSHIP_DIM_TPR) REFERENCES portal_redux.RELATIONSHIP_DIM(ID_RELATIONSHIP_DIM);


ALTER TABLE portal_redux.LICENSE_ACTION_FACT
ADD CONSTRAINT fk_LICENSE_ACTION_FACT_ID_CALENDAR_DIM_ACTION FOREIGN KEY (ID_CALENDAR_DIM_ACTION) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_LICENSE_ACTION_FACT_ID_LICENSE_ATTRIB_DIM FOREIGN KEY (ID_LICENSE_ATTRIB_DIM) REFERENCES portal_redux.LICENSE_ATTRIB_DIM(ID_LICENSE_ATTRIB_DIM),
	CONSTRAINT fk_LICENSE_ACTION_FACT_ID_PROVIDER_DIM FOREIGN KEY (ID_PROVIDER_DIM) REFERENCES portal_redux.PROVIDER_DIM(ID_PROVIDER_DIM);


ALTER TABLE portal_redux.LICENSE_FACT
ADD CONSTRAINT fk_LICENSE_FACT_ID_CALENDAR_DIM_APPLICATION FOREIGN KEY (ID_CALENDAR_DIM_APPLICATION) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_LICENSE_FACT_ID_CALENDAR_DIM_CLOSED FOREIGN KEY (ID_CALENDAR_DIM_CLOSED) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_LICENSE_FACT_ID_CALENDAR_DIM_EXPIRATION FOREIGN KEY (ID_CALENDAR_DIM_EXPIRATION) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_LICENSE_FACT_ID_CALENDAR_DIM_ISSUE FOREIGN KEY (ID_CALENDAR_DIM_ISSUE) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_LICENSE_FACT_ID_LICENSE_ATTRIB_DIM FOREIGN KEY (ID_LICENSE_ATTRIB_DIM) REFERENCES portal_redux.LICENSE_ATTRIB_DIM(ID_LICENSE_ATTRIB_DIM),
	CONSTRAINT fk_LICENSE_FACT_ID_LOCATION_DIM FOREIGN KEY (ID_LOCATION_DIM) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_LICENSE_FACT_ID_PROVIDER_DIM FOREIGN KEY (ID_PROVIDER_DIM) REFERENCES portal_redux.PROVIDER_DIM(ID_PROVIDER_DIM),
	CONSTRAINT fk_LICENSE_FACT_ID_WORKER_DIM FOREIGN KEY (ID_WORKER_DIM) REFERENCES portal_redux.WORKER_DIM(ID_WORKER_DIM);


ALTER TABLE portal_redux.PAYMENT_FACT
ADD CONSTRAINT fk_PAYMENT_FACT_ID_CALENDAR_DIM_AUTHORIZATION_BEGIN FOREIGN KEY (ID_CALENDAR_DIM_AUTHORIZATION_BEGIN) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_CALENDAR_DIM_AUTHORIZATION_END FOREIGN KEY (ID_CALENDAR_DIM_AUTHORIZATION_END) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_CALENDAR_DIM_PAYMENT_END FOREIGN KEY (ID_CALENDAR_DIM_PAYMENT_END) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_CALENDAR_DIM_PAYMENT_START FOREIGN KEY (ID_CALENDAR_DIM_PAYMENT_START) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_CALENDAR_DIM_SERVICE_BEGIN FOREIGN KEY (ID_CALENDAR_DIM_SERVICE_BEGIN) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_CALENDAR_DIM_SERVICE_END FOREIGN KEY (ID_CALENDAR_DIM_SERVICE_END) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_CALENDAR_DIM_WARRANT FOREIGN KEY (ID_CALENDAR_DIM_WARRANT) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_CASE_DIM FOREIGN KEY (ID_CASE_DIM) REFERENCES portal_redux.CASE_DIM(ID_CASE_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_LOCATION_DIM FOREIGN KEY (ID_LOCATION_DIM) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_PAYMENT_DIM FOREIGN KEY (ID_PAYMENT_DIM) REFERENCES portal_redux.PAYMENT_DIM(ID_PAYMENT_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_PEOPLE_DIM_CHILD FOREIGN KEY (ID_PEOPLE_DIM_CHILD) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_PEOPLE_DIM_CLIENT FOREIGN KEY (ID_PEOPLE_DIM_CLIENT) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_PLACEMENT_CARE_AUTH_DIM FOREIGN KEY (ID_PLACEMENT_CARE_AUTH_DIM) REFERENCES portal_redux.PLACEMENT_CARE_AUTH_DIM(ID_PLACEMENT_CARE_AUTH_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_PLACEMENT_TYPE_DIM FOREIGN KEY (ID_PLACEMENT_TYPE_DIM) REFERENCES portal_redux.PLACEMENT_TYPE_DIM(ID_PLACEMENT_TYPE_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_PROVIDER_DIM_PAYEE FOREIGN KEY (ID_PROVIDER_DIM_PAYEE) REFERENCES portal_redux.PROVIDER_DIM(ID_PROVIDER_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_PROVIDER_DIM_SERVICE FOREIGN KEY (ID_PROVIDER_DIM_SERVICE) REFERENCES portal_redux.PROVIDER_DIM(ID_PROVIDER_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_SERVICE_TYPE_DIM FOREIGN KEY (ID_SERVICE_TYPE_DIM) REFERENCES portal_redux.SERVICE_TYPE_DIM(ID_SERVICE_TYPE_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_WORKER_DIM FOREIGN KEY (ID_WORKER_DIM) REFERENCES portal_redux.WORKER_DIM(ID_WORKER_DIM);


ALTER TABLE portal_redux.PEOPLE_DIM
ADD cd_race_census INT,
	tx_race_census VARCHAR(200),
	census_hispanic_latino_origin_cd INT;


ALTER TABLE portal_redux.PEOPLE_DIM
ADD CONSTRAINT fk_PEOPLE_DIM_ID_WORKER_DIM_SSI_SSA_UPDATE FOREIGN KEY (ID_WORKER_DIM_SSI_SSA_UPDATE) REFERENCES portal_redux.WORKER_DIM(ID_WORKER_DIM);


ALTER TABLE portal_redux.PERMANENCY_FACT
ADD CONSTRAINT fk_PERMANENCY_FACT_ID_CALENDAR_DIM_HEARING FOREIGN KEY (ID_CALENDAR_DIM_HEARING) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PERMANENCY_FACT_ID_CALENDAR_DIM_ORDER_ENTERED FOREIGN KEY (ID_CALENDAR_DIM_ORDER_ENTERED) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PERMANENCY_FACT_ID_CASE_DIM FOREIGN KEY (ID_CASE_DIM) REFERENCES portal_redux.CASE_DIM(ID_CASE_DIM),
	CONSTRAINT fk_PERMANENCY_FACT_ID_LEGAL_JURISDICTION_DIM FOREIGN KEY (ID_LEGAL_JURISDICTION_DIM) REFERENCES portal_redux.LEGAL_JURISDICTION_DIM(ID_LEGAL_JURISDICTION_DIM),
	CONSTRAINT fk_PERMANENCY_FACT_ID_LEGAL_STATUS_DIM FOREIGN KEY (ID_LEGAL_STATUS_DIM) REFERENCES portal_redux.LEGAL_STATUS_DIM(ID_LEGAL_STATUS_DIM),
	CONSTRAINT fk_PERMANENCY_FACT_ID_PEOPLE_DIM FOREIGN KEY (ID_PEOPLE_DIM) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_PERMANENCY_FACT_ID_PERMANENCY_PLAN_DIM FOREIGN KEY (ID_PERMANENCY_PLAN_DIM) REFERENCES portal_redux.PERMANENCY_PLAN_DIM(ID_PERMANENCY_PLAN_DIM);


ALTER TABLE portal_redux.PLACEMENT_CARE_AUTH_FACT
ADD CONSTRAINT fk_PLACEMENT_CARE_AUTH_FACT_ID_CALENDAR_DIM_BEGIN FOREIGN KEY (ID_CALENDAR_DIM_BEGIN) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PLACEMENT_CARE_AUTH_FACT_ID_CALENDAR_DIM_END FOREIGN KEY (ID_CALENDAR_DIM_END) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PLACEMENT_CARE_AUTH_FACT_ID_PEOPLE_DIM FOREIGN KEY (ID_PEOPLE_DIM) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_PLACEMENT_CARE_AUTH_FACT_ID_PLACEMENT_CARE_AUTH_DIM FOREIGN KEY (ID_PLACEMENT_CARE_AUTH_DIM) REFERENCES portal_redux.PLACEMENT_CARE_AUTH_DIM(ID_PLACEMENT_CARE_AUTH_DIM);


ALTER TABLE portal_redux.PLACEMENT_FACT
ADD CONSTRAINT fk_PLACEMENT_FACT_ID_CALENDAR_DIM_BEGIN FOREIGN KEY (ID_CALENDAR_DIM_BEGIN) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PLACEMENT_FACT_ID_CALENDAR_DIM_END FOREIGN KEY (ID_CALENDAR_DIM_END) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PLACEMENT_FACT_ID_CALENDAR_DIM_RMVL FOREIGN KEY (ID_CALENDAR_DIM_RMVL) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PLACEMENT_FACT_ID_CASE_DIM FOREIGN KEY (ID_CASE_DIM) REFERENCES portal_redux.CASE_DIM(ID_CASE_DIM),
	CONSTRAINT fk_PLACEMENT_FACT_ID_LEGAL_STATUS_DIM FOREIGN KEY (ID_LEGAL_STATUS_DIM) REFERENCES portal_redux.LEGAL_STATUS_DIM(ID_LEGAL_STATUS_DIM),
	CONSTRAINT fk_PLACEMENT_FACT_ID_LOCATION_DIM_PLACEMENT FOREIGN KEY (ID_LOCATION_DIM_PLACEMENT) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_PLACEMENT_FACT_ID_LOCATION_DIM_REMOVAL FOREIGN KEY (ID_LOCATION_DIM_REMOVAL) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_PLACEMENT_FACT_ID_LOCATION_DIM_WORKER FOREIGN KEY (ID_LOCATION_DIM_WORKER) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_PLACEMENT_FACT_ID_PEOPLE_DIM_CHILD FOREIGN KEY (ID_PEOPLE_DIM_CHILD) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_PLACEMENT_FACT_ID_PLACEMENT_CARE_AUTH_DIM FOREIGN KEY (ID_PLACEMENT_CARE_AUTH_DIM) REFERENCES portal_redux.PLACEMENT_CARE_AUTH_DIM(ID_PLACEMENT_CARE_AUTH_DIM),
	CONSTRAINT fk_PLACEMENT_FACT_ID_PLACEMENT_RESULT_DIM FOREIGN KEY (ID_PLACEMENT_RESULT_DIM) REFERENCES portal_redux.PLACEMENT_RESULT_DIM(ID_PLACEMENT_RESULT_DIM),
	CONSTRAINT fk_PLACEMENT_FACT_ID_PLACEMENT_TYPE_DIM FOREIGN KEY (ID_PLACEMENT_TYPE_DIM) REFERENCES portal_redux.PLACEMENT_TYPE_DIM(ID_PLACEMENT_TYPE_DIM),
	CONSTRAINT fk_PLACEMENT_FACT_ID_PROVIDER_DIM_CAREGIVER FOREIGN KEY (ID_PROVIDER_DIM_CAREGIVER) REFERENCES portal_redux.PROVIDER_DIM(ID_PROVIDER_DIM),
	CONSTRAINT fk_PLACEMENT_FACT_ID_REMOVAL_EPISODE_FACT FOREIGN KEY (ID_REMOVAL_EPISODE_FACT) REFERENCES portal_redux.REMOVAL_EPISODE_FACT(ID_REMOVAL_EPISODE_FACT),
	CONSTRAINT fk_PLACEMENT_FACT_ID_SERVICE_TYPE_DIM FOREIGN KEY (ID_SERVICE_TYPE_DIM) REFERENCES portal_redux.SERVICE_TYPE_DIM(ID_SERVICE_TYPE_DIM);


ALTER TABLE portal_redux.PRIMARY_ASSIGNMENT_FACT
ADD CONSTRAINT fk_PRIMARY_ASSIGNMENT_FACT_ID_CALENDAR_DIM_BEGIN FOREIGN KEY (ID_CALENDAR_DIM_BEGIN) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PRIMARY_ASSIGNMENT_FACT_ID_CALENDAR_DIM_END FOREIGN KEY (ID_CALENDAR_DIM_END) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PRIMARY_ASSIGNMENT_FACT_ID_CASE_DIM FOREIGN KEY (ID_CASE_DIM) REFERENCES portal_redux.CASE_DIM(ID_CASE_DIM),
	CONSTRAINT fk_PRIMARY_ASSIGNMENT_FACT_ID_LOCATION_DIM FOREIGN KEY (ID_LOCATION_DIM) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_PRIMARY_ASSIGNMENT_FACT_ID_WORKER_DIM FOREIGN KEY (ID_WORKER_DIM) REFERENCES portal_redux.WORKER_DIM(ID_WORKER_DIM),
	CONSTRAINT fk_PRIMARY_ASSIGNMENT_FACT_ID_WORKER_DIM_CURRENT FOREIGN KEY (ID_WORKER_DIM_CURRENT) REFERENCES portal_redux.WORKER_DIM(ID_WORKER_DIM);


ALTER TABLE portal_redux.PROVIDER_DIM
ADD CONSTRAINT fk_PROVIDER_DIM_ID_CALENDAR_DIM_CREATED FOREIGN KEY (ID_CALENDAR_DIM_CREATED) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM);


ALTER TABLE portal_redux.PROVIDER_PART_FACT
ADD CONSTRAINT fk_PROVIDER_PART_FACT_ID_CALENDAR_DIM_END FOREIGN KEY (ID_CALENDAR_DIM_END) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PROVIDER_PART_FACT_ID_CALENDAR_DIM_START FOREIGN KEY (ID_CALENDAR_DIM_START) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PROVIDER_PART_FACT_ID_PEOPLE_DIM FOREIGN KEY (ID_PEOPLE_DIM) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_PROVIDER_PART_FACT_ID_PROVIDER_DIM_CAREGIVER FOREIGN KEY (ID_PROVIDER_DIM_CAREGIVER) REFERENCES portal_redux.PROVIDER_DIM(ID_PROVIDER_DIM);


ALTER TABLE portal_redux.PROVIDER_SERVICE_LICENSE_FACT
ADD CONSTRAINT fk_PROVIDER_SERVICE_LICENSE_FACT_ID_LICENSE_FACT FOREIGN KEY (ID_LICENSE_FACT) REFERENCES portal_redux.LICENSE_FACT(ID_LICENSE_FACT),
	CONSTRAINT fk_PROVIDER_SERVICE_LICENSE_FACT_ID_PROVIDER_DIM FOREIGN KEY (ID_PROVIDER_DIM) REFERENCES portal_redux.PROVIDER_DIM(ID_PROVIDER_DIM),
	CONSTRAINT fk_PROVIDER_SERVICE_LICENSE_FACT_ID_SERVICE_TYPE_DIM FOREIGN KEY (ID_SERVICE_TYPE_DIM) REFERENCES portal_redux.SERVICE_TYPE_DIM(ID_SERVICE_TYPE_DIM);


ALTER TABLE portal_redux.REMOVAL_EPISODE_FACT
ADD CONSTRAINT fk_REMOVAL_EPISODE_FACT_ID_CALENDAR_DIM_AFCARS_END FOREIGN KEY (ID_CALENDAR_DIM_AFCARS_END) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_REMOVAL_EPISODE_FACT_ID_CALENDAR_DIM_BEGIN FOREIGN KEY (ID_CALENDAR_DIM_BEGIN) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_REMOVAL_EPISODE_FACT_ID_CALENDAR_DIM_END FOREIGN KEY (ID_CALENDAR_DIM_END) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_REMOVAL_EPISODE_FACT_ID_CALENDAR_DIM_FIRST_HEALTH_SAFETY_VISIT FOREIGN KEY (ID_CALENDAR_DIM_FIRST_HEALTH_SAFETY_VISIT) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_REMOVAL_EPISODE_FACT_ID_CASE_DIM FOREIGN KEY (ID_CASE_DIM) REFERENCES portal_redux.CASE_DIM(ID_CASE_DIM),
	CONSTRAINT fk_REMOVAL_EPISODE_FACT_ID_LEGAL_STATUS_DIM FOREIGN KEY (ID_LEGAL_STATUS_DIM) REFERENCES portal_redux.LEGAL_STATUS_DIM(ID_LEGAL_STATUS_DIM),
	CONSTRAINT fk_REMOVAL_EPISODE_FACT_ID_LOCATION_DIM_REMOVAL FOREIGN KEY (ID_LOCATION_DIM_REMOVAL) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_REMOVAL_EPISODE_FACT_ID_LOCATION_DIM_WORKER FOREIGN KEY (ID_LOCATION_DIM_WORKER) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_REMOVAL_EPISODE_FACT_ID_PEOPLE_DIM_CHILD FOREIGN KEY (ID_PEOPLE_DIM_CHILD) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_REMOVAL_EPISODE_FACT_ID_PEOPLE_DIM_PARENT_PRIMARY FOREIGN KEY (ID_PEOPLE_DIM_PARENT_PRIMARY) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_REMOVAL_EPISODE_FACT_ID_PEOPLE_DIM_PARENT_SECONDARY FOREIGN KEY (ID_PEOPLE_DIM_PARENT_SECONDARY) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_REMOVAL_EPISODE_FACT_ID_PLACEMENT_CARE_AUTH_DIM FOREIGN KEY (ID_PLACEMENT_CARE_AUTH_DIM) REFERENCES portal_redux.PLACEMENT_CARE_AUTH_DIM(ID_PLACEMENT_CARE_AUTH_DIM),
	CONSTRAINT fk_REMOVAL_EPISODE_FACT_ID_PLACEMENT_RESULT_DIM_LATEST FOREIGN KEY (ID_PLACEMENT_RESULT_DIM_LATEST) REFERENCES portal_redux.PLACEMENT_RESULT_DIM(ID_PLACEMENT_RESULT_DIM),
	CONSTRAINT fk_REMOVAL_EPISODE_FACT_ID_REMOVAL_DIM FOREIGN KEY (ID_REMOVAL_DIM) REFERENCES portal_redux.REMOVAL_DIM(ID_REMOVAL_DIM),
	CONSTRAINT fk_REMOVAL_EPISODE_FACT_ID_WORKER_DIM_CURRENT FOREIGN KEY (ID_WORKER_DIM_CURRENT) REFERENCES portal_redux.WORKER_DIM(ID_WORKER_DIM),
	CONSTRAINT fk_REMOVAL_EPISODE_FACT_ID_WORKER_DIM_ORIGINAL FOREIGN KEY (ID_WORKER_DIM_ORIGINAL) REFERENCES portal_redux.WORKER_DIM(ID_WORKER_DIM);


ALTER TABLE portal_redux.REPEAT_MALTREATMENT_FACT
ADD CONSTRAINT fk_REPEAT_MALTREATMENT_FACT_ID_CALENDAR_DIM_PRIOR FOREIGN KEY (ID_CALENDAR_DIM_PRIOR) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_REPEAT_MALTREATMENT_FACT_ID_CALENDAR_DIM_REPEAT FOREIGN KEY (ID_CALENDAR_DIM_REPEAT) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_REPEAT_MALTREATMENT_FACT_ID_CASE_DIM FOREIGN KEY (ID_CASE_DIM) REFERENCES portal_redux.CASE_DIM(ID_CASE_DIM),
	CONSTRAINT fk_REPEAT_MALTREATMENT_FACT_ID_LOCATION_DIM_INCIDENT FOREIGN KEY (ID_LOCATION_DIM_INCIDENT) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_REPEAT_MALTREATMENT_FACT_ID_LOCATION_DIM_INTAKE_WORKER FOREIGN KEY (ID_LOCATION_DIM_INTAKE_WORKER) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_REPEAT_MALTREATMENT_FACT_ID_LOCATION_DIM_INVESTIGATION_WORKER FOREIGN KEY (ID_LOCATION_DIM_INVESTIGATION_WORKER) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_REPEAT_MALTREATMENT_FACT_ID_LOCATION_DIM_PRIMARY_WORKER FOREIGN KEY (ID_LOCATION_DIM_PRIMARY_WORKER) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_REPEAT_MALTREATMENT_FACT_ID_PEOPLE_DIM_VICTIM FOREIGN KEY (ID_PEOPLE_DIM_VICTIM) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_REPEAT_MALTREATMENT_FACT_ID_PLACEMENT_TYPE_DIM FOREIGN KEY (ID_PLACEMENT_TYPE_DIM) REFERENCES portal_redux.PLACEMENT_TYPE_DIM(ID_PLACEMENT_TYPE_DIM);


ALTER TABLE portal_redux.rptPlacement
	ADD dependency_dt                  DATETIME       NULL,
    fl_dep_exist                       INT            NULL,
    id_intake_fact                     INT            NULL,
    age_at_removal_mos                 INT            NULL,
    first_removal_dt                   DATETIME       NULL,
	latest_removal_dt                  DATETIME       NULL,
	child_eps_rank                     INT            NULL,
	child_cnt_episodes                 INT            NULL,
	cd_race_census                     INT            NULL,
	census_hispanic_latino_origin_cd   CHAR(1)		  NULL,
	initial_id_placement_fact          INT            NULL,
	longest_id_placement_fact          INT            NULL,
	next_reentry_date                  DATETIME       NULL,
	days_to_reentry                    INT            NULL,
	cd_discharge_type                  INT            NULL,
	max_bin_los_cd                     INT            NULL,
	bin_dep_cd                         INT            NULL,
	bin_ihs_svc_cd                     INT            NULL,
	dur_days                           INT            NULL,
	exit_within_month_mult3            INT            NULL,
	nxt_reentry_within_min_month_mult3 INT            NULL,
	int_filter_service_category        INT            NULL,
	filter_service_budget              INT            NULL,
	nbr_events                         INT            NULL,
	bin_placement_cd                   INT            NULL,
	nbr_ooh_events                     INT            NULL,
	init_cd_plcm_setng                 INT            NULL,
	long_cd_plcm_setng                 INT            NULL,
	pk_gndr                            INT            NULL,
	removal_county_cd                  INT            NULL,
	[18bday] 						   DATETIME       NULL;

	
ALTER TABLE portal_redux.rptPlacement_Events
	ADD id_placement_fact        INT           NULL,
    cd_srvc                      INT           NULL,
    id_plcmnt_evnt	             INT           NULL,
    cd_plcmnt_evnt               CHAR (3)      NULL,
    prtl_cd_plcm_setng           INT           NULL,
    cd_epsd_type                 INT           NULL,
    cd_end_rsn                   INT           NULL,
    derived_county               INT           NULL,
    id_provider_dim_caregiver    INT           NULL,
	[18bday] 					 DATETIME	   NULL;


ALTER TABLE portal_redux.SAFETY_ASSESSMENT_FACT
ADD CONSTRAINT fk_SAFETY_ASSESSMENT_FACT_ID_CALENDAR_DIM_APPROVAL FOREIGN KEY (ID_CALENDAR_DIM_APPROVAL) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_SAFETY_ASSESSMENT_FACT_ID_CALENDAR_DIM_INVESTIGATION_BEGIN FOREIGN KEY (ID_CALENDAR_DIM_INVESTIGATION_BEGIN) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_SAFETY_ASSESSMENT_FACT_ID_CALENDAR_DIM_INVESTIGATION_END FOREIGN KEY (ID_CALENDAR_DIM_INVESTIGATION_END) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_SAFETY_ASSESSMENT_FACT_ID_CASE_DIM FOREIGN KEY (ID_CASE_DIM) REFERENCES portal_redux.CASE_DIM(ID_CASE_DIM),
	CONSTRAINT fk_SAFETY_ASSESSMENT_FACT_ID_INTAKE_FACT FOREIGN KEY (ID_INTAKE_FACT) REFERENCES portal_redux.INTAKE_FACT(ID_INTAKE_FACT),
	CONSTRAINT fk_SAFETY_ASSESSMENT_FACT_ID_LOCATION_DIM FOREIGN KEY (ID_LOCATION_DIM) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_SAFETY_ASSESSMENT_FACT_ID_PEOPLE_DIM_CHILD FOREIGN KEY (ID_PEOPLE_DIM_CHILD) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_SAFETY_ASSESSMENT_FACT_ID_WORKER_DIM FOREIGN KEY (ID_WORKER_DIM) REFERENCES portal_redux.WORKER_DIM(ID_WORKER_DIM);


ALTER TABLE portal_redux.SERVICE_FACT
ADD CONSTRAINT fk_SERVICE_FACT_ID_CALENDAR_DIM_END FOREIGN KEY (ID_CALENDAR_DIM_END) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_SERVICE_FACT_ID_CALENDAR_DIM_START FOREIGN KEY (ID_CALENDAR_DIM_START) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_SERVICE_FACT_ID_CASE_DIM FOREIGN KEY (ID_CASE_DIM) REFERENCES portal_redux.CASE_DIM(ID_CASE_DIM),
	CONSTRAINT fk_SERVICE_FACT_ID_LOCATION_DIM_TIME_OF_APPROVAL FOREIGN KEY (ID_LOCATION_DIM_TIME_OF_APPROVAL) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_SERVICE_FACT_ID_PEOPLE_DIM_CHILD FOREIGN KEY (ID_PEOPLE_DIM_CHILD) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_SERVICE_FACT_ID_PEOPLE_DIM_SERVICE_RECIPIENT FOREIGN KEY (ID_PEOPLE_DIM_SERVICE_RECIPIENT) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_SERVICE_FACT_ID_PLACEMENT_CARE_AUTH_DIM FOREIGN KEY (ID_PLACEMENT_CARE_AUTH_DIM) REFERENCES portal_redux.PLACEMENT_CARE_AUTH_DIM(ID_PLACEMENT_CARE_AUTH_DIM),
	CONSTRAINT fk_SERVICE_FACT_ID_PLACEMENT_RESULT_DIM FOREIGN KEY (ID_PLACEMENT_RESULT_DIM) REFERENCES portal_redux.PLACEMENT_RESULT_DIM(ID_PLACEMENT_RESULT_DIM),
	CONSTRAINT fk_SERVICE_FACT_ID_PLACEMENT_TYPE_DIM FOREIGN KEY (ID_PLACEMENT_TYPE_DIM) REFERENCES portal_redux.PLACEMENT_TYPE_DIM(ID_PLACEMENT_TYPE_DIM),
	CONSTRAINT fk_SERVICE_FACT_ID_PROVIDER_DIM FOREIGN KEY (ID_PROVIDER_DIM) REFERENCES portal_redux.PROVIDER_DIM(ID_PROVIDER_DIM),
	CONSTRAINT fk_SERVICE_FACT_ID_SERVICE_TYPE_DIM FOREIGN KEY (ID_SERVICE_TYPE_DIM) REFERENCES portal_redux.SERVICE_TYPE_DIM(ID_SERVICE_TYPE_DIM);


ALTER TABLE portal_redux.SIBLING_RELATIONSHIP_FACT
ADD CONSTRAINT fk_SIBLING_RELATIONSHIP_FACT_ID_CALENDAR_DIM_BEGIN FOREIGN KEY (ID_CALENDAR_DIM_BEGIN) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_SIBLING_RELATIONSHIP_FACT_ID_CALENDAR_DIM_END FOREIGN KEY (ID_CALENDAR_DIM_END) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_SIBLING_RELATIONSHIP_FACT_ID_CASE_DIM_CHILD FOREIGN KEY (ID_CASE_DIM_CHILD) REFERENCES portal_redux.CASE_DIM(ID_CASE_DIM),
	CONSTRAINT fk_SIBLING_RELATIONSHIP_FACT_ID_PEOPLE_DIM_CHILD FOREIGN KEY (ID_PEOPLE_DIM_CHILD) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_SIBLING_RELATIONSHIP_FACT_ID_PEOPLE_DIM_SIBLING FOREIGN KEY (ID_PEOPLE_DIM_SIBLING) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM);


ALTER TABLE portal_redux.SUBSTANCE_ABUSE_WIZARD_FACT
ADD CONSTRAINT fk_SUBSTANCE_ABUSE_WIZARD_FACT_ID_PEOPLE_DIM_SUBJECT FOREIGN KEY (ID_PEOPLE_DIM_SUBJECT) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM);


ALTER TABLE portal_redux.TRAINING_FACT
ADD CONSTRAINT fk_TRAINING_FACT_ID_CALENDAR_DIM_COMPLETION FOREIGN KEY (ID_CALENDAR_DIM_COMPLETION) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_TRAINING_FACT_ID_CALENDAR_DIM_EXPIRATION FOREIGN KEY (ID_CALENDAR_DIM_EXPIRATION) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_TRAINING_FACT_ID_PEOPLE_DIM_TRAINING_PARTICIPANT FOREIGN KEY (ID_PEOPLE_DIM_TRAINING_PARTICIPANT) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_TRAINING_FACT_ID_TRAINING_TYPE_DIM FOREIGN KEY (ID_TRAINING_TYPE_DIM) REFERENCES portal_redux.TRAINING_TYPE_DIM(ID_TRAINING_TYPE_DIM);


ALTER TABLE portal_redux.TRIBE_FACT
ADD CONSTRAINT fk_TRIBE_FACT_ID_CALENDAR_DIM_ENTERED FOREIGN KEY (ID_CALENDAR_DIM_ENTERED) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_TRIBE_FACT_ID_PEOPLE_DIM FOREIGN KEY (ID_PEOPLE_DIM) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_TRIBE_FACT_ID_TRIBE_ATTRIBUTE_DIM FOREIGN KEY (ID_TRIBE_ATTRIBUTE_DIM) REFERENCES portal_redux.TRIBE_ATTRIBUTE_DIM(ID_TRIBE_ATTRIBUTE_DIM),
	CONSTRAINT fk_TRIBE_FACT_ID_TRIBE_DIM FOREIGN KEY (ID_TRIBE_DIM) REFERENCES portal_redux.TRIBE_DIM(ID_TRIBE_DIM);


ALTER TABLE portal_redux.WORKER_DIM
ADD CONSTRAINT fk_WORKER_DIM_ID_LOCATION_DIM_WORKER FOREIGN KEY (ID_LOCATION_DIM_WORKER) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_WORKER_DIM_ID_WORKER_DIM_SUPERVISOR FOREIGN KEY (ID_WORKER_DIM_SUPERVISOR) REFERENCES portal_redux.WORKER_DIM(ID_WORKER_DIM);
