-- create IL_ANSELL_CASEY_ASSESSMENT_FACT table

-- DROP TABLE portal_redux.IL_ANSELL_CASEY_ASSESSMENT_FACT;
CREATE TABLE portal_redux.IL_ANSELL_CASEY_ASSESSMENT_FACT (
	ID_IL_ANSELL_CASEY_ASSESSMENT_FACT int NOT NULL,
	ID_IL_ANSELL_CASEY_ASSESSMENT int NULL,
	ID_INDEPENDENT_LIVING_FACT int NULL,
	CD_LEVEL int NULL,
	FL_YOUTH_REFUSES int NULL,
	CONSTRAINT PK__IL_ANSEL__F61A7E709DAD682E PRIMARY KEY (ID_IL_ANSELL_CASEY_ASSESSMENT_FACT),
	CONSTRAINT fk_IL_ANSELL_CASEY_ASSESSMENT_FACT_ID_INDEPENDENT_LIVING_FACT FOREIGN KEY (ID_INDEPENDENT_LIVING_FACT) REFERENCES portal_redux.INDEPENDENT_LIVING_FACT(ID_INDEPENDENT_LIVING_FACT)
);

-- load table data

BULK INSERT portal_redux.IL_ANSELL_CASEY_ASSESSMENT_FACT
FROM 'D:\S3\fldw-in\IL_ANSELL_CASEY_ASSESSMENT_FACT.txt'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);