-- create IL_NYTD_QUESTIONS_FACT table

-- DROP TABLE portal_redux.IL_NYTD_QUESTIONS_FACT;
CREATE TABLE portal_redux.IL_NYTD_QUESTIONS_FACT (
	ID_IL_NYTD_QUESTIONS_FACT int NOT NULL,
	ID_IL_NYTD_QUESTIONS int NULL,
	ID_INDEPENDENT_LIVING_FACT int NULL,
	ID_IL_NYTD_QUESTIONS_ATTRIBUTE_DIM int NULL,
	ID_CALENDAR_DIM_SURVEY_COMPLETED int NULL,
	DT_SURVEY_COMPLETED datetime NULL,
	CONSTRAINT PK__IL_NYTD___6AD2D3A7D0DEC3EF PRIMARY KEY (ID_IL_NYTD_QUESTIONS_FACT),
	CONSTRAINT fk_IL_NYTD_QUESTIONS_FACT_ID_CALENDAR_DIM_SURVEY_COMPLETED FOREIGN KEY (ID_CALENDAR_DIM_SURVEY_COMPLETED) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_IL_NYTD_QUESTIONS_FACT_ID_IL_NYTD_QUESTIONS_ATTRIBUTE_DIM FOREIGN KEY (ID_IL_NYTD_QUESTIONS_ATTRIBUTE_DIM) REFERENCES portal_redux.IL_NYTD_QUESTIONS_ATTRIBUTE_DIM(ID_IL_NYTD_QUESTIONS_ATTRIBUTE_DIM),
	CONSTRAINT fk_IL_NYTD_QUESTIONS_FACT_ID_INDEPENDENT_LIVING_FACT FOREIGN KEY (ID_INDEPENDENT_LIVING_FACT) REFERENCES portal_redux.INDEPENDENT_LIVING_FACT(ID_INDEPENDENT_LIVING_FACT)
);

-- load table data

BULK INSERT portal_redux.IL_NYTD_QUESTIONS_FACT
FROM 'D:\S3\fldw-in\IL_NYTD_QUESTIONS_FACT.txt'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);