-- create INDEPENDENT_LIVING_BRIDGE_FACT table

-- DROP TABLE portal_redux.INDEPENDENT_LIVING_BRIDGE_FACT;
CREATE TABLE portal_redux.INDEPENDENT_LIVING_BRIDGE_FACT (
	ID_INDEPENDENT_LIVING_BRIDGE_FACT int NOT NULL,
	ID_INDEPENDENT_LIVING_FACT int NULL,
	ID_IL_SERVICE_CATEGORY_TYPE_DIM int NULL,
	CONSTRAINT PK_INDEPENDENT_LIVING_BRIDGE_FACT PRIMARY KEY (ID_INDEPENDENT_LIVING_BRIDGE_FACT)
);

-- load table data

BULK INSERT portal_redux.INDEPENDENT_LIVING_BRIDGE_FACT
FROM 'D:\S3\fldw-in\INDEPENDENT_LIVING_BRIDGE_FACT.TXT'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);