-- create INVESTIGATION_TYPE_DIM table

-- DROP TABLE portal_redux.INVESTIGATION_TYPE_DIM;
CREATE TABLE portal_redux.INVESTIGATION_TYPE_DIM (
	ID_INVESTIGATION_TYPE_DIM int NOT NULL,
	CD_INVS_TYPE int NULL,
	TX_INVS_TYPE varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DT_ROW_BEGIN datetime NULL,
	DT_ROW_END datetime NULL,
	ID_CYCLE int NULL,
	IS_CURRENT int NULL,
	CONSTRAINT PK_ID_INVESTIGATION_TYPE_DIM PRIMARY KEY (ID_INVESTIGATION_TYPE_DIM)
);

-- load table data

BULK INSERT portal_redux.INVESTIGATION_TYPE_DIM
FROM 'D:\S3\fldw-in\INVESTIGATION_TYPE_DIM.TXT'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);