-- create LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT table

-- DROP TABLE portal_redux.LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT;
CREATE TABLE portal_redux.LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT (
	ID_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT int NOT NULL,
	ID_LEGAL_AGGRAVATED_CIRCUMSTANCES int NULL,
	ID_CASE_DIM int NULL,
	ID_PEOPLE_DIM int NULL,
	ID_CALENDAR_DIM_FINDING int NULL,
	FL_ADOPTION_NOT_APPROPRIATE tinyint NULL,
	FL_AGGRV_CIRCUMSTANCE_EXISTS tinyint NULL,
	FL_COMP_REASON_EXISTS tinyint NULL,
	FL_NO_RSNBL_EFFORT_CT_FINDING tinyint NULL,
	FL_PROGRESS tinyint NULL,
	FL_OTHER_TPR_REASON tinyint NULL,
	ID_CASE int NULL,
	ID_PRSN int NULL,
	CONSTRAINT PK_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT PRIMARY KEY (ID_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT),
	CONSTRAINT fk_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT_ID_CALENDAR_DIM_FINDING FOREIGN KEY (ID_CALENDAR_DIM_FINDING) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT_ID_CASE_DIM FOREIGN KEY (ID_CASE_DIM) REFERENCES portal_redux.CASE_DIM(ID_CASE_DIM),
	CONSTRAINT fk_LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT_ID_PEOPLE_DIM FOREIGN KEY (ID_PEOPLE_DIM) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM)
);

-- load table data

BULK INSERT portal_redux.LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT
FROM 'D:\S3\fldw-in\LEGAL_AGGRAVATED_CIRCUMSTANCES_FACT.txt'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);