-- create LEGAL_FACT table

-- DROP TABLE portal_redux.LEGAL_FACT;
CREATE TABLE portal_redux.LEGAL_FACT (
	ID_LEGAL_FACT int NOT NULL,
	ID_CRT_DISP int NULL,
	ID_CALENDAR_DIM_EFFECTIVE int NULL,
	ID_CALENDAR_DIM_HEARING int NULL,
	ID_CASE_DIM int NULL,
	ID_LEGAL_ACTION_DIM int NULL,
	ID_LEGAL_JURISDICTION_DIM int NULL,
	ID_LEGAL_RESULT_DIM int NULL,
	ID_LEGAL_STATUS_DIM int NULL,
	ID_PEOPLE_DIM int NULL,
	ID_WORKER_DIM int NULL,
	FL_REASONABLE_EFFORT_FINALIZE_PERMANENCY tinyint NULL,
	FL_REASONABLE_EFFORT_PREVENT_REMOVAL tinyint NULL,
	TS_UP datetime NULL,
	ID_PRSN int NULL,
	ID_CASE int NULL,
	CONSTRAINT PK_ID_LEGAL_FACT PRIMARY KEY (ID_LEGAL_FACT),
	CONSTRAINT fk_LEGAL_FACT_ID_CALENDAR_DIM_EFFECTIVE FOREIGN KEY (ID_CALENDAR_DIM_EFFECTIVE) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_LEGAL_FACT_ID_CALENDAR_DIM_HEARING FOREIGN KEY (ID_CALENDAR_DIM_HEARING) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_LEGAL_FACT_ID_CASE_DIM FOREIGN KEY (ID_CASE_DIM) REFERENCES portal_redux.CASE_DIM(ID_CASE_DIM),
	CONSTRAINT fk_LEGAL_FACT_ID_LEGAL_ACTION_DIM FOREIGN KEY (ID_LEGAL_ACTION_DIM) REFERENCES portal_redux.LEGAL_ACTION_DIM(ID_LEGAL_ACTION_DIM),
	CONSTRAINT fk_LEGAL_FACT_ID_LEGAL_JURISDICTION_DIM FOREIGN KEY (ID_LEGAL_JURISDICTION_DIM) REFERENCES portal_redux.LEGAL_JURISDICTION_DIM(ID_LEGAL_JURISDICTION_DIM),
	CONSTRAINT fk_LEGAL_FACT_ID_LEGAL_RESULT_DIM FOREIGN KEY (ID_LEGAL_RESULT_DIM) REFERENCES portal_redux.LEGAL_RESULT_DIM(ID_LEGAL_RESULT_DIM),
	CONSTRAINT fk_LEGAL_FACT_ID_LEGAL_STATUS_DIM FOREIGN KEY (ID_LEGAL_STATUS_DIM) REFERENCES portal_redux.LEGAL_STATUS_DIM(ID_LEGAL_STATUS_DIM),
	CONSTRAINT fk_LEGAL_FACT_ID_PEOPLE_DIM FOREIGN KEY (ID_PEOPLE_DIM) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_LEGAL_FACT_ID_WORKER_DIM FOREIGN KEY (ID_WORKER_DIM) REFERENCES portal_redux.WORKER_DIM(ID_WORKER_DIM)
);
CREATE NONCLUSTERED INDEX NonClusteredIndex-20140326-102159 ON dbo.LEGAL_FACT (  ID_LEGAL_ACTION_DIM ASC  , ID_LEGAL_RESULT_DIM ASC  , ID_LEGAL_STATUS_DIM ASC  )  
	INCLUDE ( ID_CALENDAR_DIM_EFFECTIVE , ID_CALENDAR_DIM_HEARING ) 
	WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	ON [PRIMARY];
CREATE NONCLUSTERED INDEX idx_id_legal_result_dim ON dbo.LEGAL_FACT (  ID_LEGAL_RESULT_DIM ASC  )  
	INCLUDE ( ID_CALENDAR_DIM_EFFECTIVE , ID_LEGAL_ACTION_DIM , ID_LEGAL_STATUS_DIM , ID_PRSN ) 
	WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	ON [PRIMARY];
CREATE NONCLUSTERED INDEX idx_id_prsn_legal_fact_incl_eff_hearing_status ON dbo.LEGAL_FACT (  ID_PRSN ASC  )  
	INCLUDE ( ID_CALENDAR_DIM_EFFECTIVE , ID_CALENDAR_DIM_HEARING , ID_LEGAL_STATUS_DIM ) 
	WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	ON [PRIMARY];
CREATE NONCLUSTERED INDEX idx_legal_fact_ID_LEGAL_RESULT_DIM_INCL ON dbo.LEGAL_FACT (  ID_LEGAL_RESULT_DIM ASC  )  
	INCLUDE ( ID_CALENDAR_DIM_EFFECTIVE , ID_CALENDAR_DIM_HEARING , ID_CASE , ID_LEGAL_ACTION_DIM , ID_LEGAL_STATUS_DIM , ID_PRSN ) 
	WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	ON [PRIMARY];
CREATE NONCLUSTERED INDEX idx_legal_fact_id_legal_result_dim ON dbo.LEGAL_FACT (  ID_LEGAL_RESULT_DIM ASC  )  
	INCLUDE ( ID_CALENDAR_DIM_EFFECTIVE , ID_LEGAL_FACT , ID_LEGAL_JURISDICTION_DIM , ID_PRSN ) 
	WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	ON [PRIMARY];

-- load table data

BULK INSERT portal_redux.LEGAL_FACT
FROM 'D:\S3\fldw-in\LEGAL_FACT.TXT'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);