-- create PROVIDER_SERVICE_LICENSE_FACT table

-- DROP TABLE portal_redux.PROVIDER_SERVICE_LICENSE_FACT;
CREATE TABLE portal_redux.PROVIDER_SERVICE_LICENSE_FACT (
	ID_PROVIDER_SERVICE_LICENSE_FACT int NOT NULL,
	ID_BSNS int NULL,
	ID_LCNS int NULL,
	ID_PRVD_ORG int NULL,
	ID_LICENSE_FACT int NULL,
	ID_PROVIDER_DIM int NULL,
	ID_SERVICE_TYPE_DIM int NULL,
	CD_SRVC int NULL,
	QT_LCNS_CAP int NULL,
	CONSTRAINT PK_ID_PROVIDER_SERVICE_LICENSE_FACT PRIMARY KEY (ID_PROVIDER_SERVICE_LICENSE_FACT),
	CONSTRAINT fk_PROVIDER_SERVICE_LICENSE_FACT_ID_LICENSE_FACT FOREIGN KEY (ID_LICENSE_FACT) REFERENCES portal_redux.LICENSE_FACT(ID_LICENSE_FACT),
	CONSTRAINT fk_PROVIDER_SERVICE_LICENSE_FACT_ID_PROVIDER_DIM FOREIGN KEY (ID_PROVIDER_DIM) REFERENCES portal_redux.PROVIDER_DIM(ID_PROVIDER_DIM),
	CONSTRAINT fk_PROVIDER_SERVICE_LICENSE_FACT_ID_SERVICE_TYPE_DIM FOREIGN KEY (ID_SERVICE_TYPE_DIM) REFERENCES portal_redux.SERVICE_TYPE_DIM(ID_SERVICE_TYPE_DIM)
);

-- load table data

BULK INSERT portal_redux.PROVIDER_SERVICE_LICENSE_FACT
FROM 'D:\S3\fldw-in\PROVIDER_SERVICE_LICENSE_FACT.txt'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);