-- create WORKER_DIM table

-- DROP TABLE portal_redux.WORKER_DIM;
CREATE TABLE portal_redux.WORKER_DIM (
	ID_WORKER_DIM int NOT NULL,
	ID_PRSN int NULL,
	ID_PRSN_SPRV int NULL,
	ID_RMTS_GROUP_COORD int NULL,
	ID_LOCATION_DIM_WORKER int NULL,
	ID_WORKER_DIM_SUPERVISOR int NULL,
	CD_JOB_CLS int NULL,
	TX_JOB_CLS varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_RMTS_WRKR_TYP int NULL,
	TX_RMTS_WRKR_TYP varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_STAT char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TX_STAT varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_UNT int NULL,
	QT_WRK_MEASURE int NULL,
	DT_BRTH datetime NULL,
	DT_END datetime NULL,
	DT_START datetime NULL,
	DT_ROW_BEGIN datetime NULL,
	DT_ROW_END datetime NULL,
	ID_CYCLE int NULL,
	IS_CURRENT int NULL,
	CONSTRAINT PK_ID_WORKER_DIM PRIMARY KEY (ID_WORKER_DIM),
	CONSTRAINT fk_WORKER_DIM_ID_LOCATION_DIM_WORKER FOREIGN KEY (ID_LOCATION_DIM_WORKER) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_WORKER_DIM_ID_WORKER_DIM_SUPERVISOR FOREIGN KEY (ID_WORKER_DIM_SUPERVISOR) REFERENCES portal_redux.WORKER_DIM(ID_WORKER_DIM)
);

-- load table data

BULK INSERT portal_redux.WORKER_DIM
FROM 'D:\S3\fldw-in\WORKER_DIM.txt'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);