-- create CASE_DIM table

-- DROP TABLE portal_redux.CASE_DIM;
CREATE TABLE portal_redux.CASE_DIM (
	ID_CASE_DIM int NOT NULL,
	ID_CASE int NULL,
	ID_CALENDAR_DIM_LAST_ACTIVITY int NULL,
	ID_LOCATION_DIM int NULL,
	CD_CASE_STAT char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TX_CASE_STAT varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_CASE_TYPE int NULL,
	TX_CASE_TYPE varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_DCF_WRK_INV char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TX_DCF_WRK_INV varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DT_CASE_CLS datetime NULL,
	DT_CASE_OPN datetime NULL,
	DT_ROW_BEGIN datetime NULL,
	DT_ROW_END datetime NULL,
	ID_CYCLE int NULL,
	IS_CURRENT int NULL,
	FL_DELETED char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FL_EXPUNGED char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FL_TRIBAL_IVE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK_CASE_DIM PRIMARY KEY (ID_CASE_DIM),
	CONSTRAINT fk_CASE_DIM_ID_CALENDAR_DIM_LAST_ACTIVITY FOREIGN KEY (ID_CALENDAR_DIM_LAST_ACTIVITY) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_CASE_DIM_ID_LOCATION_DIM FOREIGN KEY (ID_LOCATION_DIM) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM)
);

-- load table data

BULK INSERT portal_redux.CASE_DIM
FROM 'D:\S3\fldw-in\CASE_DIM.TXT'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);