-- create EDUCATION_PLAN_DIM table

-- DROP TABLE portal_redux.EDUCATION_PLAN_DIM;
CREATE TABLE portal_redux.EDUCATION_PLAN_DIM (
	ID_EDUCATION_PLAN_DIM int NOT NULL,
	CD_ACADEM_GOALS int NULL,
	TX_ACADEM_GOALS varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_ACADEM_PROGRESS int NULL,
	TX_ACADEM_PROGRESS varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_ED_ROLE int NULL,
	TX_ED_ROLE varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_ISSUES_PROGRESS int NULL,
	TX_ISSUES_PROGRESS varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_PLAN_CREDITS int NULL,
	TX_PLAN_CREDITS varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_PREP_POST_ED int NULL,
	TX_PREP_POST_ED varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_PROVIDED_BY int NULL,
	TX_PROVIDED_BY varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_RES_ROLE int NULL,
	TX_RES_ROLE varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_SERVICES_NEEDED int NULL,
	TX_SERVICES_NEEDED varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_TRANSPORT int NULL,
	TX_TRANSPORT varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DT_ROW_BEGIN datetime NULL,
	DT_ROW_END datetime NULL,
	ID_CYCLE int NULL,
	IS_CURRENT int NULL,
	CONSTRAINT PK_ID_EDUCATION_PLAN_DIM PRIMARY KEY (ID_EDUCATION_PLAN_DIM)
);

-- load table data

BULK INSERT portal_redux.EDUCATION_PLAN_DIM
FROM 'D:\S3\fldw-in\EDUCATION_PLAN_DIM.TXT'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);