-- create INDEPENDENT_LIVING_FACT table

-- DROP TABLE portal_redux.INDEPENDENT_LIVING_FACT;
CREATE TABLE portal_redux.INDEPENDENT_LIVING_FACT (
	ID_INDEPENDENT_LIVING_FACT int NOT NULL,
	ID_INDEPENDENT_LIVING int NULL,
	ID_PRSN int NULL,
	ID_CALENDAR_DIM_ANTICIPATED_OUT_CARE int NULL,
	ID_CALENDAR_DIM_BEGAN int NULL,
	ID_CALENDAR_DIM_IL_PLAN_COMPLETED int NULL,
	ID_CALENDAR_DIM_INITIAL_IL_REFERRAL int NULL,
	ID_CALENDAR_DIM_REFERRED int NULL,
	ID_CALENDAR_DIM_YOUTH_NOT_PARTICIPATING int NULL,
	ID_PEOPLE_DIM int NULL,
	FL_YOUTH_REFERRED int NULL,
	FL_YOUTH_RECEIVING int NULL,
	FL_YOUTH_NOT_PARTICIPATING int NULL,
	CONSTRAINT PK__INDEPEND__260A77248D1A691D PRIMARY KEY (ID_INDEPENDENT_LIVING_FACT),
	CONSTRAINT fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_ANTICIPATED_OUT_CARE FOREIGN KEY (ID_CALENDAR_DIM_ANTICIPATED_OUT_CARE) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_BEGAN FOREIGN KEY (ID_CALENDAR_DIM_BEGAN) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_IL_PLAN_COMPLETED FOREIGN KEY (ID_CALENDAR_DIM_IL_PLAN_COMPLETED) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_INITIAL_IL_REFERRAL FOREIGN KEY (ID_CALENDAR_DIM_INITIAL_IL_REFERRAL) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_REFERRED FOREIGN KEY (ID_CALENDAR_DIM_REFERRED) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INDEPENDENT_LIVING_FACT_ID_CALENDAR_DIM_YOUTH_NOT_PARTICIPATING FOREIGN KEY (ID_CALENDAR_DIM_YOUTH_NOT_PARTICIPATING) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INDEPENDENT_LIVING_FACT_ID_PEOPLE_DIM FOREIGN KEY (ID_PEOPLE_DIM) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM)
);

-- load table data

BULK INSERT portal_redux.INDEPENDENT_LIVING_FACT
FROM 'D:\S3\fldw-in\INDEPENDENT_LIVING_FACT.TXT'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);