-- create INTAKE_VICTIM_FACT table

-- DROP TABLE portal_redux.INTAKE_VICTIM_FACT;
CREATE TABLE portal_redux.INTAKE_VICTIM_FACT (
	ID_INTAKE_VICTIM_FACT int NOT NULL,
	ID_ACCESS_REPORT int NULL,
	ID_INVS int NULL,
	ID_PRSN_VCTM int NULL,
	ID_INTAKE_FACT int NULL,
	ID_CALENDAR_DIM_IFF_RESPONSE_ATTEMPT int NULL,
	ID_CALENDAR_DIM_IFF_RESPONSE_COMPLETED int NULL,
	ID_CALENDAR_DIM_VICTIM_ADDED int NULL,
	ID_PEOPLE_DIM_CHILD int NULL,
	ID_RESPONSE_TIME_EXP_DIM int NULL,
	CD_ACTIVITY_LOCATION_IFF int NULL,
	TX_ACTIVITY_LOCATION_IFF varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ACTUAL_RESPONSE_TIME int NULL,
	ATTEMPTED_RESPONSE_TIME int NULL,
	DT_IFF_ATTEMPTED datetime NULL,
	DT_IFF_COMPLETED datetime NULL,
	DT_VICTIM_ADDED datetime NULL,
	FL_EXPUNGED char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DT_DUE_ORIGINAL datetime NULL,
	DT_DUE datetime NULL,
	ID_CALENDAR_DIM_DUE_ORIGINAL int NULL,
	ID_CALENDAR_DIM_DUE int NULL,
	FL_EXCEPTION tinyint NULL,
	FL_EXTENSION tinyint NULL,
	FL_IFF_REQUIRED tinyint NULL,
	ID_CALENDAR_DIM_EXTENSION int NULL,
	DT_EXTENSION datetime NULL,
	ID_CASE int NULL,
	ID_PRVD_ORG_INTAKE int NULL,
	ID_FACP int NULL,
	id_prsn_child int NULL,
	CONSTRAINT PK_INTAKE_VICTIM_FACT PRIMARY KEY (ID_INTAKE_VICTIM_FACT),
	CONSTRAINT fk_INTAKE_VICTIM_FACT_ID_CALENDAR_DIM_DUE FOREIGN KEY (ID_CALENDAR_DIM_DUE) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INTAKE_VICTIM_FACT_ID_CALENDAR_DIM_DUE_ORIGINAL FOREIGN KEY (ID_CALENDAR_DIM_DUE_ORIGINAL) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INTAKE_VICTIM_FACT_ID_CALENDAR_DIM_IFF_RESPONSE_ATTEMPT FOREIGN KEY (ID_CALENDAR_DIM_IFF_RESPONSE_ATTEMPT) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INTAKE_VICTIM_FACT_ID_CALENDAR_DIM_IFF_RESPONSE_COMPLETED FOREIGN KEY (ID_CALENDAR_DIM_IFF_RESPONSE_COMPLETED) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INTAKE_VICTIM_FACT_ID_CALENDAR_DIM_VICTIM_ADDED FOREIGN KEY (ID_CALENDAR_DIM_VICTIM_ADDED) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_INTAKE_VICTIM_FACT_ID_RESPONSE_TIME_EXP_DIM FOREIGN KEY (ID_RESPONSE_TIME_EXP_DIM) REFERENCES portal_redux.RESPONSE_TIME_EXP_DIM(ID_RESPONSE_TIME_EXP_DIM),
	CONSTRAINT fk_INTAKE_VICTIM_FACT_IID_CALENDAR_DIM_VICTIM_ADDED FOREIGN KEY (ID_CALENDAR_DIM_VICTIM_ADDED) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM)
);

-- load table data

BULK INSERT portal_redux.INTAKE_VICTIM_FACT
FROM 'D:\S3\fldw-in\INTAKE_VICTIM_FACT.TXT'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);