-- create PAYMENT_FACT table

-- DROP TABLE portal_redux.PAYMENT_FACT;
CREATE TABLE portal_redux.PAYMENT_FACT (
	ID_PAYMENT_FACT int NOT NULL,
	ID_PMNT int NULL,
	ID_SSPS_AUTH int NULL,
	ID_SSPS_PAYEE_ID int NULL,
	ID_SSPS_PRVD_ID int NULL,
	ID_AUTHORIZATION_FACT int NULL,
	ID_CALENDAR_DIM_AUTHORIZATION_BEGIN int NULL,
	ID_CALENDAR_DIM_AUTHORIZATION_END int NULL,
	ID_CALENDAR_DIM_PAYMENT_END int NULL,
	ID_CALENDAR_DIM_PAYMENT_START int NULL,
	ID_CALENDAR_DIM_SERVICE_BEGIN int NULL,
	ID_CALENDAR_DIM_SERVICE_END int NULL,
	ID_CALENDAR_DIM_WARRANT int NULL,
	ID_CASE_DIM int NULL,
	ID_LOCATION_DIM int NULL,
	ID_PAYMENT_DIM int NULL,
	ID_PEOPLE_DIM_CHILD int NULL,
	ID_PEOPLE_DIM_CLIENT int NULL,
	ID_PLACEMENT_CARE_AUTH_DIM int NULL,
	ID_PLACEMENT_TYPE_DIM int NULL,
	ID_PROVIDER_DIM_PAYEE int NULL,
	ID_PROVIDER_DIM_SERVICE int NULL,
	ID_SERVICE_TYPE_DIM int NULL,
	ID_WORKER_DIM int NULL,
	CD_SSPS_REGION_CODE int NULL,
	CD_SSPS_RPT_UNIT int NULL,
	AM_RATE float NULL,
	AM_TOTAL_PAID float NULL,
	AM_UNITS float NULL,
	CHILD_AGE int NULL,
	ID_PRSN_CHILD int NULL,
	ID_PRSN_CLIENT int NULL,
	ID_PRVD_ORG_PAYEE int NULL,
	ID_PRVD_ORG_SERVICE int NULL,
	id_case int NULL,
	CONSTRAINT PK_ID_PAYMENT_FACT PRIMARY KEY (ID_PAYMENT_FACT),
	CONSTRAINT fk_PAYMENT_FACT_ID_CALENDAR_DIM_AUTHORIZATION_BEGIN FOREIGN KEY (ID_CALENDAR_DIM_AUTHORIZATION_BEGIN) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_CALENDAR_DIM_AUTHORIZATION_END FOREIGN KEY (ID_CALENDAR_DIM_AUTHORIZATION_END) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_CALENDAR_DIM_PAYMENT_END FOREIGN KEY (ID_CALENDAR_DIM_PAYMENT_END) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_CALENDAR_DIM_PAYMENT_START FOREIGN KEY (ID_CALENDAR_DIM_PAYMENT_START) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_CALENDAR_DIM_SERVICE_BEGIN FOREIGN KEY (ID_CALENDAR_DIM_SERVICE_BEGIN) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_CALENDAR_DIM_SERVICE_END FOREIGN KEY (ID_CALENDAR_DIM_SERVICE_END) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_CALENDAR_DIM_WARRANT FOREIGN KEY (ID_CALENDAR_DIM_WARRANT) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_CASE_DIM FOREIGN KEY (ID_CASE_DIM) REFERENCES portal_redux.CASE_DIM(ID_CASE_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_LOCATION_DIM FOREIGN KEY (ID_LOCATION_DIM) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_PAYMENT_DIM FOREIGN KEY (ID_PAYMENT_DIM) REFERENCES portal_redux.PAYMENT_DIM(ID_PAYMENT_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_PEOPLE_DIM_CHILD FOREIGN KEY (ID_PEOPLE_DIM_CHILD) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_PEOPLE_DIM_CLIENT FOREIGN KEY (ID_PEOPLE_DIM_CLIENT) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_PLACEMENT_CARE_AUTH_DIM FOREIGN KEY (ID_PLACEMENT_CARE_AUTH_DIM) REFERENCES portal_redux.PLACEMENT_CARE_AUTH_DIM(ID_PLACEMENT_CARE_AUTH_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_PLACEMENT_TYPE_DIM FOREIGN KEY (ID_PLACEMENT_TYPE_DIM) REFERENCES portal_redux.PLACEMENT_TYPE_DIM(ID_PLACEMENT_TYPE_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_PROVIDER_DIM_PAYEE FOREIGN KEY (ID_PROVIDER_DIM_PAYEE) REFERENCES portal_redux.PROVIDER_DIM(ID_PROVIDER_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_PROVIDER_DIM_SERVICE FOREIGN KEY (ID_PROVIDER_DIM_SERVICE) REFERENCES portal_redux.PROVIDER_DIM(ID_PROVIDER_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_SERVICE_TYPE_DIM FOREIGN KEY (ID_SERVICE_TYPE_DIM) REFERENCES portal_redux.SERVICE_TYPE_DIM(ID_SERVICE_TYPE_DIM),
	CONSTRAINT fk_PAYMENT_FACT_ID_WORKER_DIM FOREIGN KEY (ID_WORKER_DIM) REFERENCES portal_redux.WORKER_DIM(ID_WORKER_DIM)
);
CREATE NONCLUSTERED INDEX idx_am_total_paid ON dbo.PAYMENT_FACT (  AM_TOTAL_PAID ASC  )  
	INCLUDE ( AM_RATE , AM_UNITS , ID_CALENDAR_DIM_SERVICE_BEGIN , ID_CALENDAR_DIM_SERVICE_END , id_case , ID_PAYMENT_FACT , ID_PROVIDER_DIM_SERVICE , ID_PRSN_CHILD , ID_SERVICE_TYPE_DIM ) 
	WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	ON [PRIMARY];
CREATE NONCLUSTERED INDEX idx_payment_fact_am_total_paid_incl7 ON dbo.PAYMENT_FACT (  AM_TOTAL_PAID ASC  )  
	INCLUDE ( ID_CALENDAR_DIM_SERVICE_BEGIN , ID_CALENDAR_DIM_SERVICE_END , ID_PAYMENT_FACT , ID_PROVIDER_DIM_SERVICE , ID_PRSN_CHILD , ID_SERVICE_TYPE_DIM ) 
	WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	ON [PRIMARY];
CREATE NONCLUSTERED INDEX idx_payment_fact_prov_svc_prsn_paid_incl3 ON dbo.PAYMENT_FACT (  ID_PROVIDER_DIM_SERVICE ASC  , ID_SERVICE_TYPE_DIM ASC  , ID_PRSN_CHILD ASC  , AM_TOTAL_PAID ASC  )  
	INCLUDE ( ID_CALENDAR_DIM_SERVICE_BEGIN , ID_CALENDAR_DIM_SERVICE_END , ID_PAYMENT_FACT ) 
	WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	ON [PRIMARY];
CREATE NONCLUSTERED INDEX idx_provider_srvc_child_incl_srvc_dates ON dbo.PAYMENT_FACT (  ID_PROVIDER_DIM_SERVICE ASC  , ID_PRSN_CHILD ASC  )  
	INCLUDE ( AM_RATE , AM_TOTAL_PAID , AM_UNITS , ID_CALENDAR_DIM_SERVICE_BEGIN , ID_CALENDAR_DIM_SERVICE_END , ID_PAYMENT_FACT , ID_SERVICE_TYPE_DIM ) 
	WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	ON [PRIMARY];
CREATE NONCLUSTERED INDEX idx_std_id_prsn_child_payment_fact ON dbo.PAYMENT_FACT (  ID_SERVICE_TYPE_DIM ASC  )  
	INCLUDE ( ID_PRSN_CHILD ) 
	WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	ON [PRIMARY];

-- load table data

BULK INSERT portal_redux.PAYMENT_FACT
FROM 'D:\S3\fldw-in\PAYMENT_FACT.TXT'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);