-- create SAFETY_ASSESSMENT_FACT table

-- DROP TABLE portal_redux.SAFETY_ASSESSMENT_FACT;
CREATE TABLE portal_redux.SAFETY_ASSESSMENT_FACT (
	ID_SAFETY_ASSESSMENT_FACT int NOT NULL,
	ID_SFTY_ASMNT_PART int NULL,
	ID_SFTY_ASMNT_PLAN int NULL,
	ID_INTAKE_FACT int NULL,
	ID_CALENDAR_DIM_APPROVAL int NULL,
	ID_CALENDAR_DIM_INVESTIGATION_BEGIN int NULL,
	ID_CALENDAR_DIM_INVESTIGATION_END int NULL,
	ID_CASE_DIM int NULL,
	ID_LOCATION_DIM int NULL,
	ID_PEOPLE_DIM_CHILD int NULL,
	ID_WORKER_DIM int NULL,
	CD_SDM_CALCULATED_RISK_LEVEL int NULL,
	TX_SDM_CALCULATED_RISK_LEVEL varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_SDM_FINAL_RISK_LEVEL int NULL,
	TX_SDM_FINAL_RISK_LEVEL varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_SDM_OVERRIDE_RISK_LEVEL int NULL,
	TX_SDM_OVERRIDE_RISK_LEVEL varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CD_SDM_OVERRIDE_RISK_LEVEL_REASON int NULL,
	TX_SDM_OVERRIDE_RISK_LEVEL_REASON varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FL_REQUIRED_SAFETY_ASSESSMENT tinyint NULL,
	FL_RISK_LEVEL_OVERRIDE tinyint NULL,
	FL_SAFETY_FACTOR1 tinyint NULL,
	FL_SAFETY_FACTOR2 tinyint NULL,
	FL_SAFETY_FACTOR3 tinyint NULL,
	FL_SAFETY_FACTOR4 tinyint NULL,
	FL_SAFETY_FACTOR5 tinyint NULL,
	FL_SAFETY_FACTOR6 tinyint NULL,
	FL_SAFETY_FACTOR7 tinyint NULL,
	FL_SAFETY_FACTOR8 tinyint NULL,
	FL_SAFETY_PLAN_EXISTS tinyint NULL,
	QT_ABUSE_SCORE int NULL,
	QT_DAYS_UNTIL_START int NULL,
	QT_NEGLECT_SCORE int NULL,
	FL_EXPUNGED char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ID_CASE int NULL,
	ID_PRSN_CHILD int NULL,
	CONSTRAINT PK_ID_SAFETY_ASSESSMENT_FACT PRIMARY KEY (ID_SAFETY_ASSESSMENT_FACT),
	CONSTRAINT fk_SAFETY_ASSESSMENT_FACT_ID_CALENDAR_DIM_APPROVAL FOREIGN KEY (ID_CALENDAR_DIM_APPROVAL) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_SAFETY_ASSESSMENT_FACT_ID_CALENDAR_DIM_INVESTIGATION_BEGIN FOREIGN KEY (ID_CALENDAR_DIM_INVESTIGATION_BEGIN) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_SAFETY_ASSESSMENT_FACT_ID_CALENDAR_DIM_INVESTIGATION_END FOREIGN KEY (ID_CALENDAR_DIM_INVESTIGATION_END) REFERENCES portal_redux.CALENDAR_DIM(ID_CALENDAR_DIM),
	CONSTRAINT fk_SAFETY_ASSESSMENT_FACT_ID_CASE_DIM FOREIGN KEY (ID_CASE_DIM) REFERENCES portal_redux.CASE_DIM(ID_CASE_DIM),
	CONSTRAINT fk_SAFETY_ASSESSMENT_FACT_ID_INTAKE_FACT FOREIGN KEY (ID_INTAKE_FACT) REFERENCES portal_redux.INTAKE_FACT(ID_INTAKE_FACT),
	CONSTRAINT fk_SAFETY_ASSESSMENT_FACT_ID_LOCATION_DIM FOREIGN KEY (ID_LOCATION_DIM) REFERENCES portal_redux.LOCATION_DIM(ID_LOCATION_DIM),
	CONSTRAINT fk_SAFETY_ASSESSMENT_FACT_ID_PEOPLE_DIM_CHILD FOREIGN KEY (ID_PEOPLE_DIM_CHILD) REFERENCES portal_redux.PEOPLE_DIM(ID_PEOPLE_DIM),
	CONSTRAINT fk_SAFETY_ASSESSMENT_FACT_ID_WORKER_DIM FOREIGN KEY (ID_WORKER_DIM) REFERENCES portal_redux.WORKER_DIM(ID_WORKER_DIM)
);

-- load table data

BULK INSERT portal_redux.SAFETY_ASSESSMENT_FACT
FROM 'D:\S3\fldw-in\SAFETY_ASSESSMENT_FACT.TXT'
WITH (
    firstrow = 2,
    fieldterminator = '|',
    rowterminator = '\n'
);